### ISSUE TITLE
[Bug]: Cryogenic oversight consoles appear invisible.

### ISSUE THREAD

**Issue by h42-real** [BeeStation/BeeStation-Hornet#10084]
### BYOND Version

514.1589

### Round Date

2023/10/23

### Round ID

46344

### Test merges

- #9124 
- #9337 
- #10059

### Describe the bug

Cryogenic oversight consoles have no sprite when created.  Can likely be solved with a fix similar to #10015 .

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/104878598/852a8e05-eec8-4b8f-b586-08a9d8b4b72d)

### What did you expect?

I expected the console to use the intended sprite for itself, rather than nothing.

### Reproducible steps

- Right click where a cryogenic oversight console would be
- See that it is invisible

**Comment by Fronsis** [comment]
If it's not invisible sometimes it looks like this
![Screenshot_12 (1)](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/91583071-f1d5-4e75-a79e-010a2b53b3d2)

**Comment by Fronsis** [comment]
Guh not the stale label uhhh @PowerfulBacon pinging you because you might notify it to anyone that knows about spriting or what causes it and it seems it also affects https://github.com/BeeStation/BeeStation-Hornet/issues/10098 in away

Tbh i feel it's slightly important because that machine get used to retrieve items (sometimes a CE cryo's with the BP's and that's the only way to get them back, making the traitor objective denied if that happens, similar cases could be warden gloves, det belongings, cap medal and so forth) alongside checking who cryo'd to help with investigation or who's just gone
