### ISSUE TITLE
[Bug]: Wooden tables are not made of wood anymore

### ISSUE THREAD

**Issue by WhereAmO** [BeeStation/BeeStation-Hornet#10353]
### Round Date

2023/12/19

### Round ID

47038

### Describe the bug

When attempting to create wooden tables via applying wooden planks to a table frame, I get a weird iron table instead that drops no items (save iron rods) when broken.

### What did you expect?

A lovely wooden table, not an ugly iron one.

### Reproducible steps

1. Make table frame
2. Apply wood
3. Get broken (iron?) table

**Comment by Tsar-Salat** [comment]
> When attempting to create wooden tables via applying wooden planks to a table frame

Wooden tables are made using wooden frames. 

Attempting to make a wooden table out of an iron frame uses the basemats system, which is confused because wood currently exists in a weird limbo of being a material used for structure, but not being a basemat.

I had a plan to make a pr for wooden tables within the month, Ill accelerate it for tonight.

**Comment by WhereAmO** [comment]
I'm sorry there's a wooden table frame now or has that always been a thing?..

**Comment by Tsar-Salat** [comment]
> I'm sorry there's a wooden table frame now or has that always been a thing?..

That's how they've always been made

**Comment by Tsar-Salat** [comment]
> I had a plan to make a pr for turning wood into a basemat within the month, Ill accelerate it for tonight.

Liar
