### ISSUE TITLE
Intelligence potion icon problem

### ISSUE THREAD

**Issue by Bleueue** [BeeStation/BeeStation-Hornet#10676]
Issue reported from  Round ID: 47872 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Lost the image. Tried to put a Intelligence potion into my belt slot. Items turn red when they can't go in a place. The red icon of the intelligence potion appeared over the belt slot, and never left even after I moved it to my backpack.

**Comment by aramix273** [comment]
found how to replicate and it's not unique to intelligence potions, belt slot, or even item compatibility:
1. have item in active hand
2. hover over an item slot so that a highlight appears
3. click and drag out of the slot
4. highlight remains permanently

attached replication video:

https://github.com/BeeStation/BeeStation-Hornet/assets/27755442/d7f04765-3e3f-4901-bf27-2022e3c23113

one might ask what happens if I close and reopen clothing slots - the highlights persist even through that, but are not visible while closed (unlike forcedly removed hardsuit helmets for example)
