### ISSUE TITLE
(ignore this)

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#10702]
wrote something wrong. Ignore this

**Comment by EvilDragonfiend** [comment]
```dm
/datum/timedevent/proc/bucketJoin()
	// Generate debug-friendly name for timer
	var/static/list/bitfield_flags = list("TIMER_UNIQUE", "TIMER_OVERRIDE", "TIMER_CLIENT_TIME", "TIMER_STOPPABLE", "TIMER_NO_HASH_WAIT", "TIMER_LOOP")
	name = "Timer: [id] ([FAST_REF(src)]), TTR: [timeToRun], wait:[wait] Flags: [jointext(bitfield_to_list(flags, bitfield_flags), ", ")], \
		callBack: [FAST_REF(callBack)], callBack.object: [callBack.object][FAST_REF(callBack.object)]([getcallingtype()]), \
		callBack.delegate:[callBack.delegate]([callBack.arguments ? callBack.arguments.Join(", ") : ""]), source: [source]"
```

This can be a source of the reason why timer subsystem is so slow.

**Comment by EvilDragonfiend** [comment]
Elevated to VERY IMPORTANT because subsystems can be slower with this thing...

**Comment by EvilDragonfiend** [comment]
I wrote something wrong

**Comment by PowerfulBacon** [comment]
Even if it was faster, the speeds that we are talking are probably never going to be in the range of nanosecond improvements per minute which isn't worth it for the absolutely horrible code readability. Also I swear interpolation is faster since adding strings together creates unnecessary strings in the string tree?
