### ISSUE TITLE
[Bug]: stamina damage is not limited to 100

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#11322]
### Describe the bug

Something I've noticed is that, when stamina damage is applied via any traditional method (batons, disablers, drugs), the value is no longer limited to 100, and can go way beyond that.

This sometimes even has the effect where the damage will get stuck at an arbitrary value above 100, which results in players getting stuck in the knocked-down state for longer than expected. 

Most cases I've seen eventually resolve, but when VV'ing them, it clearly is not lowering naturally.

Likely from #10083 

### What did you expect?

I expected stamina damage to be capped at 100, and for it to decrease at a reasonable rate.

**Comment by Tsar-Salat** [comment]
Actually, I might be wrong here. Is it additively combining all the limb damages?

**Comment by PowerfulBacon** [comment]
Stamina damage is fine to surpass 100, however once you enter stam crit a timer starts since your last attack which is about 3 or 4 seconds, and it resets every time yoy get attacked. Once that timer ends you will immediately heal out of stamina crit no matter your stamina damage so 120 and 180 stamina damage should recover in the same amount of time

**Comment by TsunamiAnt** [comment]
maybe that isn't what's happening then? I saw a few people stuck at like 120 stamina for 10 or so minutes...
