### ISSUE TITLE
Update TGUI

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#1582]
Right now, our UIs are a mixture of old original tgui and tgui-next. TG has announced their latest and greatest refactor for the near future, tgui 3.0: https://github.com/tgstation/tgstation/pull/50497

This is a bounty to bring bee's UIs fully up-to-date with 3.0 tgui and remove old tgui. TGUI 3.0 is significantly faster than old tgui, easier to develop for, and looks better.

Specific requirements to fulfill the bounty:

- Port the tgui 3.0 refactor
- Update/convert *every* tgui/tgui-next UI beestation has to tgui 3.0. Even if TG doesn't have a 3.0 version of it (which should only be 1 or 2 small UIs).
- Any HTML UIs that have been converted to tgui 3.0 by TG must also be converted here. This just consists of porting conversions from TG.
- Every UI must be functional. The bounty PR will be testmerged to ensure this condition is met.
- Old tgui/tgui-next code must be fully removed.

**Comment by ike709** [comment]
Shoutout to @jlsnow301 for being cool.

**Comment by qwertyquerty** [comment]
The madman

**Comment by Crossedfall** [comment]
Currently being worked on by @stylemistake

**Comment by stylemistake** [comment]
Progress.

![image](https://user-images.githubusercontent.com/1516236/80049436-8f1ee800-851b-11ea-8076-87646471826f.png)

Easily cherry-pickable things were already cherry-picked, whole tgui module folders were nuked and replaced, so what's left is basically game objects that need conflict resolving since they are so out of sync.

And there are *a lot* of them.

[Preview of already working UIs](https://media.discordapp.net/attachments/490307354353467423/701994210231844864/unknown.png).

More news at ten.
