### ISSUE TITLE
Dragging mulebots

### ISSUE THREAD

**Issue by JAremko** [BeeStation/BeeStation-Hornet#178]
If you hack a mulebot loader and put a person on it and start dragging the person you will also drag the mulebot.  The best part is that if you also hack bot's safety you'll be able to crush people with it.  Speed(motor) hack also seems to work.

**Comment by Kerbin-Fiber** [comment]
I don't see how this is an issue at all, this is how MULEBots work

**Comment by yorii** [comment]
Confirmed as not stale, but also is more extensive than this, as you cannot even unbuckle a mob buckled to the mulebot.
Disarm intent also pushes said mob around, despite the fact that mulebots cannot be pushed around.

**Comment by Chessus** [comment]
@Crossedfall Clone of [50841](https://github.com/tgstation/tgstation/issues/50841) fixed by [50970](https://github.com/tgstation/tgstation/pull/50970) Fixes pulling issue.

Disarm push still works on current tg. 

Current tg code has a [riding refactor](https://github.com/tgstation/tgstation/pull/54183) and a big [mobility refactor](https://github.com/tgstation/tgstation/pull/54183)  which would make harder for me to code in the falling off by downed players/mob

**Comment by PowerfulBacon** [comment]
#3374
