### ISSUE TITLE
Explosive Lance Borked

### ISSUE THREAD

**Issue by FancyPak** [BeeStation/BeeStation-Hornet#2158]
Issue reported from  Round ID: 18717 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

When making explosive lance you dont use up the grenade, and sometimes it breaks by thinking you still have a spear in your other hand

**Comment by eLeCtrOssSnake** [comment]
It may be creating an invisible as such happens with other crafting recipes, but other than that I did not see anything work somehow else. Also, the possibility of not taking the item is close to zero because in crafting code it actually finds the items, and then deletes them. I do not see any edge cases where you can end up crafting something without consuming crafting materials.
