### ISSUE TITLE
putting floor tiles on water tiles was a horrible mistake

### ISSUE THREAD

**Issue by niceping** [BeeStation/BeeStation-Hornet#276]
Round ID: I don't think it's necessary, but I'll put it anyways. 5809

Desc: Title.
![BeeStation - For Beginners! Low RP Chaotic Fun! crew killing station 2019-07-27 182439](https://user-images.githubusercontent.com/40269243/61992662-3ad5fd00-b09c-11e9-8bd7-2224494457a9.png)

Reproduction: Spawn as hotel employee or get there by teleport. Get floor tile from anywhere. Place it in pool. Done.

The most epic part is that I reported this issue on /tg/ almost year ago, but it wasn't fixed. (https://github.com/tgstation/tgstation/issues/39503)

**Comment by niceping** [comment]
And yes in case if you wondered I do have CSS installed

**Comment by ike709** [comment]
>And yes in case if you wondered I do have CSS installed

Bruh.

**Comment by qwertyquerty** [comment]
I think he means cs:source

**Comment by qwertyquerty** [comment]
I'll look into this

**Comment by ike709** [comment]
You probably shouldn't be able to put tiles on them at all, so just modify the water tile's subtype for whatever handles tile placement (presumably attackby?) to return early.

**Comment by yorii** [comment]
Confirmed as not stale, but also is probably intentional, inspecting the water yields this information:

That's some water.
You get the feeling that nobody's bothered to actually make this water functional...
You might be able to build ontop of it with some tiles...

Texture bug in original post is not occuring:
![image](https://user-images.githubusercontent.com/7960287/87309858-75d77780-c51d-11ea-910f-376cd7e62352.png)

**Comment by Crossedfall** [comment]
Building on water is intentional, yeah. The texture bug was fixed sometime in December. Closing as the texture issue is resolved
