### ISSUE TITLE
Remove Pubby shit thermo sm, return to tesla

### ISSUE THREAD

**Issue by LastCrusader105** [BeeStation/BeeStation-Hornet#2801]
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/ good one im banned

on LRP at least it always delams cause not many know what they are doing with it station goes down hill, I think we should either make it so its standard sm like before, OR we just add a new area down south and add the equipment for a tesla

**Comment by ghost** [comment]
The issue is that the chamber starts as a vaccum so the Crystal will start to deteriorate after about 10 minutes after the round started.

**Comment by LastCrusader105** [comment]
We will just add tesla

**Comment by ghost** [comment]
> We will just add tesla

That's literally worse.

**Comment by FortSumter** [comment]
I think after the PR for the NSV reactors is merged they'll replace the SM with it on pubby, and possibly all other stations. They are better than SM because they don't delam instantly, but worse because if they melt down it irradiates the entire station instead of just causing hallucinations.

**Comment by MNarath1** [comment]
its funny cause its not hard to use that sm just accept that delaming it is part of the job and mod the cooling loop so you can stop the delam whenever you want

**Comment by MNarath1** [comment]
a setup i am normally going for is putting heat exchange mainfold pipes inside the sm chamber all 3 layers connecting them with the plasma cooling loop with a valve and a volume pump that pumps the gas out of the sm cooling loop back into the plasma loop so that if i heat it again the plasma in the pipe does not inhibit the burning hellfire that i am going to unleash in the sm again until i cool it down later works great and usually gives me usually around 3-5 mw of power only drawback is you gonna check on the sm once in a while and the ai and rest of engineering will often scream at you that the sm is delaming while you have to keep assuring them that it is fine
