### ISSUE TITLE
Plasma man can't breathe after cloning. 

### ISSUE THREAD

**Issue by FortSumter** [BeeStation/BeeStation-Hornet#2893]
Issue reported from  Round ID: 23680 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1536

Not sure what happened as ahelp was not answered to determine some important variables and the body was incinerated before I died.

I was pre-ejected at 90% cloning with my limbs intact due to a power failure. I was placed under a shower and provided a full plasma tank and internals, however I still suffocated and spent the entire round in medical and no one could figure out what was wrong.

From what I understand, limbs grow last after organs during the cloning process, meaning my lungs were intact when I was ejected. I know I was given plasma man lungs because any other type of lungs will deteriorate in a plasma man till non-functional ( AKA death).

Some research may be needed to be conducted on this, as either I don't know something basic here, or the cloning process for plasmemes is borked, making it impossible to clone them.

**Comment by LastCrusader105** [comment]
I too had this issue but was died before I could investigate further

**Comment by LastCrusader105** [comment]
also cheif plasmeme helmets arnt heatproof @zeskorion fix please plasmeme god

**Comment by PowerfulBacon** [comment]
hm highly possible that they are given standard human lungs.

**Comment by FortSumter** [comment]
No. If I was given human lungs, then I wouldn't get the special plasma indicator plasmemes get when they aren't breathing plasma and instead get the normal no O2 symbol other races get when suffocating. I would also be dying of severe organ failure and not just suffocation, as replacing the plasmemes lungs with ANY OTHER KIND make the new lungs rapidly decay.

**Comment by FortSumter** [comment]
I have not since played plasma man and so I have no idea if this was a fluke or an ongoing problem, nor may ever do so again due to them not being defib-able.

**Comment by Chessus** [comment]
I could recreate this. I believe it was cloneloss effecting your oxyloss. You didn't mention recieving cryo/rezadone

I ejected the clone at around 90% (fully pugraded cloner, disabled apc)
It had roughly 18 clone damage. I checked the lungs variable and they were not damaged.
I gave them rezadone and it was completely healed and they started to breath again (Oxyloss went down, it was staying put otherwise). 
![cloneloss 1](https://user-images.githubusercontent.com/10277607/104145864-61186580-5414-11eb-82bb-141b7a94b93a.PNG)
![cloneloss 2](https://user-images.githubusercontent.com/10277607/104145867-62e22900-5414-11eb-847c-a41eb6abc5f3.PNG)
Turns out cloneloss increases when you don't heal it, even on a stasis bed. It increased the oxyloss also
![cloneloss 3](https://user-images.githubusercontent.com/10277607/104145894-768d8f80-5414-11eb-9a1b-5e9ebe0c7ecf.PNG)
@PowerfulBacon I think this can cbe closed, although I couldn't find in the code where cloneloss causes oxyloss.

**Comment by Chessus** [comment]
Edit: Tried recreating it again today but with no luck. At the time healing the clone loss stoped the suffocation. 

From testing today, at 85-95% the lungs were fully formed. There was only cloneloss. I compared the lung variables to a healthy plasmaman and the species references were different.
