### ISSUE TITLE
Make battle royal automatically start if restart is delayed.

### ISSUE THREAD

**Issue by Unidentified-Biohazard** [BeeStation/BeeStation-Hornet#3060]
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/

**Comment by Sinestia** [comment]
Bad idea imo 

 I prefer ctf too, and no one cares if CTF is just instantly culled because the delay was only like a minute. BR has a little bit more investment imo ?

**Comment by Unidentified-Biohazard** [comment]
I enjoy battle royal more, has more at play. not to mention a lot more people partake in battle royal than in CTF.

**Comment by jlsnow301** [comment]
Bounty'd, I remember discussing this in ooc (maybe with you)

**Comment by St0rmC4st3r** [comment]
Aw man. If only this was not bountysource.

**Comment by PowerfulBacon** [comment]
This would probably be a super easy thing to code, but maybe an option for the admins to trigger it when they delay would be better, since sometimes there can be a ticket that will take 2 minutes or something. Also should probably include an option to set how long the game will last and change the speed of the wall accordingly. 

Other things that arent in scope for this for br would be cuts possibly just loading a custom map for it, since the station after it has been blown to pieces is not a good place to battle on due to all the depressurisation, general loot improvements and possibly no collisions with other players during the first part of the game.

**Comment by jlsnow301** [comment]
> but maybe an option for the admins to trigger it when they delay would be better, since sometimes there can be a ticket that will take 2 minutes or something.

This would be nice if the admin gets a popup on delaying, otherwise I can see them just skipping it.
Also: The actual BR doesn't even have to end, just gives players something to do (in my opinion)
And I think pressure doesn't affect fortniters idk

**Comment by PowerfulBacon** [comment]
I might give it a go, but make it optional for the admins and make it enter sudden death mode with a super-fast wall upon all tickets being completed.

**Comment by PowerfulBacon** [comment]
> 
> 
> > but maybe an option for the admins to trigger it when they delay would be better, since sometimes there can be a ticket that will take 2 minutes or something.
> 
> This would be nice if the admin gets a popup on delaying, otherwise I can see them just skipping it.
> Also: The actual BR doesn't even have to end, just gives players something to do (in my opinion)
> And I think pressure doesn't affect fortniters idk

Made it a popup to admins that have the R_FUN perm (Everyone except trialmins) and the wall will go into maxspeed mode when all tickets are resolved.
