### ISSUE TITLE
Sleepy pens and Blood Toxicity interact strangely

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3216]
https://github.com/BeeStation/BeeStation-Hornet/blob/2467386bb666982dd41cb5e6acb4b1ebc4e392f3/code/modules/reagents/chemistry/reagents/other_reagents.dm#L32

https://forums.beestation13.com/t/blood-toxicity-needs-to-be-reworked/9832/11

**Comment by Sinestia** [comment]
https://github.com/tgstation/tgstation/pull/52019 

tg fixed it here and I copied it in one of my branches
culprit is that reaction line in pen.dm on injection

i'd submit a pr but all I have is that one change, and not the rest because we don't have the refactor. But hey if that's fine then it seems to work in my testing
