### ISSUE TITLE
$200 Bounty - Lavaland..........

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3262]
Yeah I don't like it. It's too isolated, the station is blowing up and miners are in Timbuktu. They have no incentive to actually contribute (by shooting rock, not getting gamer loot, mind you). I bountied [#1061](https://github.com/BeeStation/BeeStation-Hornet/pull/1061) because of this, but honestly it's just... Not enough. With #2551 in the works, it would be nicer to synergize the two departments.

**So, shopping list:**

1. Mineable asteroids
2. ~~Shaft~~ Asteroid miners are science now
3.  They start in the science shuttle room
4. They get a small shuttle to the "starter" asteroid with limited resources
5. Custom shuttles can get to new asteroids.
6. These asteroids have more mats and dangerous mobs. Yes you can leave megafauna in, if you like.
7. Lavaland delete

**Comment by TeomanTheGreat** [comment]
So your method of solving the isolation of lavaland is by making people go to isolated asteroids? Also before lavaland mining did take place on an asteroid.

**Comment by ike709** [comment]
Better idea is to have a big room in the station exposed to space with an asteroid magnet that "pulls in" aka generates a procedural asteroid. Or just have them spawn in space around the station and periodically get fresh ones.

**Comment by jlsnow301** [comment]
> Better idea is to have a big room in the station exposed to space with an asteroid magnet that "pulls in" aka generates a procedural asteroid. 

one of the original thoughts was strapping lavaland to the shuttle like this. i don't like the mining z-level completely detached and I think it'd actually be a performance boon. using asteroids was just a way to merge with shuttles somehow

**Comment by ike709** [comment]
Y'know an _even better_ idea would be nuking mining entirely and replacing it with a """salvage""" department that goes around in a shuttle after https://github.com/BeeStation/BeeStation-Hornet/pull/2551 and blasts & salvages enemy ships for materials. Salvaging would be automatic after killing an enemy, a la FTL.

**Comment by jlsnow301** [comment]
> Y'know an _even better_ idea would be nuking mining entirely and replacing it with a """salvage""" department that goes around in a shuttle after https://github.com/BeeStation/BeeStation-Hornet/pull/2551 and blasts & salvages enemy ships for materials. Salvaging would be automatic after killing an enemy, a la FTL.

?wyci
Because both of these ideas are appealing to me

**Comment by jlsnow301** [comment]
For all intents and purposes, the requests are just suggestions. I think mining is boring, lonely, doesn't synergize with science. If you use my implementation, ike's, or have a better one, I'm game

**Comment by ghost** [comment]
i want muh megafaunas to fight :(

**Comment by jlsnow301** [comment]
> i want muh megafaunas to fight :(

See number 6

Edit holy fuck GitHub text

**Comment by TeomanTheGreat** [comment]
> Better idea is to have a big room in the station exposed to space with an asteroid magnet that "pulls in" aka generates a procedural asteroid. Or just have them spawn in space around the station and periodically get fresh ones.

Isn't that what goon does?

**Comment by jlsnow301** [comment]
>So your method of solving the isolation of lavaland is by making people go to isolated asteroids? Also before lavaland mining did take place on an asteroid.

mining as it stands is tucked away in the furthest recesses of the cargo department, only by technicality that they are "supply". They have little interaction with cargo other than their protolathe. Basically, they get a little room, they fuck off for the entire round, during which science just pings over radio every so often "mats please", "are miners dead?", "do we have miners?" 

So, it's not necessarily _isolated_ in the sense that they're on a different dimension (though, that is an issue too), they're isolated because they just disappear and barely need to interact with anyone else, and nearly all other departments with a lathe depend on them (edit: them being <3 people).

**Comment by Fronsis** [comment]
Alright i talked this a lil bit with you on the PR channel and my on conclusion i think my ideal scenario to give Lavaland a little bit more of activity but that you don't afk on another level and never come back to the station would be to expand Lavaland itself adding some extra ruins, mobs, loot 

It would be like Scientist need to go to the Science outpost on lavaland with their own shuttle, why would they go? Well because this new lavaland now has mini ruins or loot that once it gets back into the lavaland science outpost they can be discovered and award Research Points, and perhaps if the system were to be like the strange object the scientist could also get to use the discovered thing that would do X or Y stuff and sometimes if those ruins have mobs around em they would need to get the help of the miners to clear it out, in anycase it's just another science thing for them to do which fits with the theme

Regarding the meteors and such i think you could wait until either the Bluespace exploration pr made by Bacon or the gateway from Caecilius gets done, i think i linked them to you yesterday on the pr discussion channel, i don't think lavaland needs to be removed because... it's quite iconic, adding more stuff? sure! as qwerty one said... improve don't remove

**Comment by badideaguy** [comment]
lavaland has gamer loot, pod dudes, golem dudes,lizard dudes, vet dudes, and you say it is isolated? Also you can mine asteroids currently,  just go into space with a gps to find you way back, asteroids still contain ore, and is very isolated

**Comment by Fronsis** [comment]
> Implying vet dudes or pod dudes can leave
The only ones they could see are lizards

In any case i think he implies miners themselves regarding the station 

ofc  i don't think it's worth going into random asteroids (they're quite rare ) and barely have ores

**Comment by badideaguy** [comment]
Well, in my experience power gaming is the most effective lure for cooperation and interaction, and miners are famous for power gaming
Power creep go brrrrrr

**Comment by jlsnow301** [comment]
> lavaland has gamer loot, pod dudes, golem dudes,lizard dudes, vet dudes, and you say it is isolated? 

it's also a totally different game on a totally different dimension

**Comment by ghost** [comment]
Not to mention, lavaland consumes a ton of processing power for a single job and a few ghost roles that aren't even guranteed to spawn every round.

**Comment by PowerfulBacon** [comment]
It would be relatively easy to add to bluespace exploration system to make them have a ship that can fly to asteroids each game. That way we can still have ruins, have megafauna every now and then and have encounters with ghost roles, but the pace of them can be controlled which means miners will have to mine to get to the point rather than rush megafauna and leave the station resourceless. 
Actually now that I read the post this is exactly what you describe with and the framework in https://github.com/BeeStation/BeeStation-Hornet/pull/2551 is perfect for this
```
    Mineable asteroids
    Shaft Asteroid miners are science now
    They start in the science shuttle room
    They get a small shuttle to the "starter" asteroid with limited resources
    Custom shuttles can get to new asteroids.
    These asteroids have more mats and dangerous mobs. Yes you can leave megafauna in, if you like.
    Lavaland delete
```

**Comment by jlsnow301** [comment]
> It would be relatively easy to add to bluespace exploration 

of course I'm on board, but the golden question is whether this (and your bluespace PR) fits within a one-hour round window

**Comment by VictorVow** [comment]
> So your method of solving the isolation of lavaland is by making people go to isolated asteroids? 

Lavaland can only be reached via the gulag shuttle or mining shuttle. From there you need a GPS and to track down a miner through ashstorms, hostile fauna and environmental hazards before you can assassinate them, if that was your traitor objective.

I'm not sure exactly how Bacon's BSE PR will work with this but I expect it to be simpler in that there are several shuttles available roundstart, antags will have options to buy/quickly create/modify existing ones so that they can be usable, and then simply pilot the shuttle to the asteroid that a miner is on. 

That's on the antag side. But on the miner side too they can be incentivised to be less isolated and come back to the station more frequently e.g. needing to refuel their ship, perhaps limiting ore box space (why is it infinite?), maybe loot system can be reworked to require stuff from the vendor to unlock it etc. This would make it more akin to xenobio/viro isolation in that they *do* spend most of the time alone doing their job, but also frequently visit their actual department to give and get things.

**Comment by PowerfulBacon** [comment]
Is anyone working on this?

**Comment by ike709** [comment]
I'm assigning this bounty to Bacon, since I think extending the custom shuttle content is the best way to handle this and he's already done 90% of the work.

**Comment by PowerfulBacon** [comment]
im pretty sure someone was working on something for it

**Comment by ike709** [comment]
If someone _is_ working on this, they need to come forward ASAP with what their plan for this bounty is and get approval or there's a good chance it'll get closed and their effort will be wasted.

**Comment by jlsnow301** [comment]
no one has made me aware of any efforts towards this

**Comment by ghost** [comment]
if it's not taken I'm up for taking this, I did some code similar to this for NSV. I'd agree with Ike that a mineral magnet is a better call because you can generate the asteroids better.

feel free to contact me on discord at qustinnus#8423 if interested, I don't usually code for Bee but I'm sure Ike or someone else can vouch for my expertise with TG codebases.

**Comment by Qustinnus** [comment]
if it's not taken I'm up for taking this, I did some code similar to this for NSV. I'd agree with Ike that a mineral magnet is a better call because you can generate the asteroids better.

feel free to contact me on discord at qustinnus#8423 if interested, I don't usually code for Bee but I'm sure Ike or someone else can vouch for my expertise with TG codebases.

**Comment by PowerfulBacon** [comment]
Im thinking of giving it a go with the infinite generation system of BSE now that its done however I don't feel particularly confident on actually finishing but whatever.
Somethings to consider
 - Megafauna
 - Any reasons to return to the station?
 - Any progression so you can't roundstart go for loot and ignore mining
 - Mining tool rebalance / new mining tools required (probably ones to find them)
 - Any challenge / interesting things?
 - How many different types of things can you find
 - Loot (Need some actual effort for it)
 - GHOST ROLES! <-- pretty important imo

**Comment by VictorVow** [comment]
> Any reasons to return to the station?

Ideally more reasons than there are already since otherwise if you have an objective to kill/impersonate a miner it's extremely difficult to. Vendor on station with tendril chest keys, regular refueling and reducing ore box capacity down from infinite are possibilities.

> Any progression so you can't roundstart go for loot and ignore mining

Should probably be balanced so that *antag* miners can get loot earlier to help complete objectives but non-antags would have to wait until later. Maybe not tendrils but megafauna accessible roundstart, and traitor miners having access to items that helps kill them. 

Also not mentioned is gulag. Not sure how this can be done in a way that miners can't instantly break out any prisoners.

**Comment by TeomanTheGreat** [comment]
> Also not mentioned is gulag. Not sure how this can be done in a way that miners can't instantly break out any prisoners. 

Space gulag on an asteroid perhaps (with the labor shuttle leading to it)?

**Comment by jlsnow301** [comment]
> Somethings to consider
> 
> * Megafauna

they're fun, and I don't think they need removed, it wouldn't be breaking immersion to just put them elsewhere. i thought about lairs as an option, ie: upgraded shuttle can transport to bubblegum lair, etc. so long as departments are working in tandem it's good

> * Any reasons to return to the station?

haul resources, upgrades, I guess. i think areas should be gated behind research, as above?

> * Any progression so you can't roundstart go for loot and ignore mining

above

> * Mining tool rebalance / new mining tools required (probably ones to find them)

if there's going to be pirates and so forth, yes, miners would become more like shuttle defense while en route

> * Any challenge / interesting things?

kind of like random maints, surely

> * How many different types of things can you find

unlimited

> * Loot (Need some actual effort for it)

current gear could be kept in (and possibly rebalanced)

> * GHOST ROLES! <-- pretty important imo

space pirates now have a pretty neat objective. i also think it'd make a little more sense to encounter syndicate (rather than randomly on LL)

**Comment by PowerfulBacon** [comment]
> unlimited

there's never going to be unlimited different types of things you can find
