### ISSUE TITLE
[TGUISTAT] Incompatible with WINE/Linux

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#3363]
Stat panel is completely missing with this test merge. Chat box itself still visible/

**Comment by ike709** [comment]
~~I'm really tired of having to support IE8.~~

**Comment by ike709** [comment]
I'm going to assume it's because IE8 doesn't seem to support flex. Could be other issues though.

Either way I'll bug bacon to fix it ASAP.

**Comment by PowerfulBacon** [comment]
Without flex it is going to look disgusting, Ill try and make it as good as I can for IE8 users, I know TGchat is slightly worse on WINE/Linux since it doesn't support flex but at the moment I am having trouble ordering the verbs in a decent manner.
Making it into a vertical list is very easy for Linux users, however, making it into the nice ordered panels they are now is really hard without flex.
