### ISSUE TITLE
Feature Request: Shadowling

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#353]
They are good ok pls port

**Comment by qwertyquerty** [comment]
Aren't nightmares basically shadowling v2

**Comment by Kevak** [comment]
No. Nightmares are a massive downgrade. Nightmares are a halfassed sideantag that has no objectiveset, no endgoal, and is more or less just a valid assistant that can go through walls and can't use pockets. Shadowlings were originally removed by the TG maintainer who made them because he had a massive tantrum and removed all the shit he'd done before leaving. Nobody bothered readding them. Shadowlings are a fully fledged conversion antag that feels and plays very much differently from anything  we  currently have.

Compare:

https://wiki.hippiestation.com/index.php/Shadowling

https://wiki.beestation13.com/view/Nightmare

**Comment by yorii** [comment]
Cool idea, ask someone to port it.

**Comment by TeomanTheGreat** [comment]
Please someone port it

**Comment by yorii** [comment]
no need to close this!
