### ISSUE TITLE
Warping grey crossbreeds producing invisible slimes from composite color cores

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#3811]
Don't remember the round ID or the test merges, but this bug has been there since slime warping crossbreeds were introduced, and last I tried this some days ago it still happened.

Reproduction:
Make a rune from a warping grey slime crossbreed, and drop 8 light pink or dark blue extracts on top of it. When activated, it won't produce a normal slime of that color, but rather an invisible "lightpink" or "darkblue" slime. They still work just like normal slimes, being able to reproduce into even more bugged slimes and attack players. 

Didn't test it with dark purple, other colors seem to work fine.

**Comment by francinum** [comment]
The issue is from the fact that the icon state is determined through a different process to the rest of the slime structure. I assume the same would happen to dark purple.

https://github.com/BeeStation/BeeStation-Hornet/blob/b3d1ef930be506289c2c0f345557167c834bf7b2/code/modules/mob/living/simple_animal/slime/slime.dm#L115-L121
the solution is thusly to sanitize the color string immediately, and retool `icons/mob/slimes.dmi` to index icon by sanitized color.

**Comment by kingcaine2** [comment]
I Love eating my wife's pussy

**Comment by ZombieNub** [comment]
I can personally verify that this happens with dark purple as well. I just faced this bug ingame.
