### ISSUE TITLE
Obese debuff time decrease

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3874]
Eating two bites of a botany creation should not cause your character to walk at half speed for the entire shift

**Comment by MitztheKat** [comment]
I want fat to be easier to be removed without having medical access *cough* INSULIN *cough*
The best route would be weights that go through nutrition really fast, so you can go to dorms, use the weights for a couple of minutes, then walk out feeling fit again
I think there is a virus that makes everyone super hungry. What if there was a threshold that stabilized the nutrition loss to only when stuffed? 
Another idea is the nanite thing which eats fat when overweight to be easier to obtain OR a crude version that just takes fat and no nanite gain early on.
I personally could possibly make insulin mixable in chemistry cheaply and nerf how fast it goes through fat.
another idea is if my memory serves correctly, doesn't the lipid extractor machine exist and makes synthmeat instead of human meat? if so, I'd make a pre-game tip to build one early on when the research appears to gain easy meat for steaks.
This problem has many complex solutions, but not many suitable easy ones.

**Comment by Archanial** [comment]
Just build lipid extractor or find one in maints.

**Comment by jlsnow301** [comment]
> Just build lipid extractor or find one in maints.

i think the description ("run around the station") should be made accurate

**Comment by MitztheKat** [comment]
> > Just build lipid extractor or find one in maints.
> i think the description ("run around the station") should be made accurate



there is a serious issue with fatness outside of medbay. Botany is often the main supplier of food (chef dies, bartender has no access, cargo refuses to order pizza) and often makes potency 120 apples that anhilate starvation into stuffed in one bite. 
To assume that you can simply crawl through maintenance to find a lipid extractor guaranteed, HA. Some roles don't have maint access and it's not guaranteed, PLUS crawling through maints looking for it is SLOW.
I'm going to stop you here Archanial, there IS a serious problem, and if you don't code it I will on my own codebase.
