### ISSUE TITLE
Gas Filter broken

### ISSUE THREAD

**Issue by yorii** [BeeStation/BeeStation-Hornet#4023]
## Reproduction:

![image](https://user-images.githubusercontent.com/7960287/113353630-446a3a80-933e-11eb-8ca4-23d1b68e2379.png)

**Comment by PowerfulBacon** [comment]
The reason for this most likely is that there is no tritium in the pipe. Your output pipe feeds back into the chamber, but the chamber is of ridiculous pressure so the outlet pipe wont actually output any gasses leading to the pressure in the forward direction being incredibly high, the gas filter can't push gas into the output if the pressure on the other side is too high meaning it can't function at all.
If you want tritium to come out you need to set the air alarm to filter only tritium rather than looping out any bad gasses back in.
