### ISSUE TITLE
IPC  brain ending up in hell

### ISSUE THREAD

**Issue by Aderez** [BeeStation/BeeStation-Hornet#4026]
## Round ID:
28437

On sage
## Testmerges:
#3993: '[PORT] Emissivity Blockers' by francinum at commit b868d8270d
#3984: 'Syndicate station 13' by PowerfulBacon at commit df4692a1ee

## Reproduction:
Went to robo after arm got blown off, player proceeds to do organ manipulation and remove my brain out of sheer incompetency, for some reason he kept saying the brain was "catatonic" despite me being able to enter my body, that being the brain, and it should of been revivable, yet the brain flavortext says "This one seems particularly lifeless. Perhaps it will gain it's luster later." even when I am currently inside it. I kept going from a view of the robo lab to the null room, probably because of being in his backpack or something similar?

Removing an IPC's brain using surgery I'd assume, and then putting said brain in a container, don't know exactly what's going on but that's my best guess

**Comment by RDS88-beeman** [comment]
As far as I can tell this is just kind of... a thing that happens. Removing IPC brains is a BIG "Don't do it", because if you put it back, in any body, it gets sent to Brazil. In addition, the brain flavortext is also a thing that happens, but for everyone.

Nobody wants to fix this because IPC's are shitcode upon shitcode upon shitcode

**Comment by ItsTisme** [comment]
IPC (insanly poop coded)

**Comment by Kapu1178** [comment]
Fixed 2 weeks ago
