### ISSUE TITLE
Issue: Kilo Rework 

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#416]
## Round ID:
Unknown/All

## Testmerges:
It's in primary right now

## Reproduction:
Clone Tube has two directional, ID-restricted glass sliding doors, which no one has access to.
Even if it were working, it looks neat but makes it hard for cloning: You have to open the door and grab the clone in seconds before it begins the close animation.
I'd suggest replacing these with just one reinforced glass panel, if any at all

**Comment by jlsnow301** [comment]
@prophed

**Comment by prophed** [comment]
Yeah, my idea was too have a tiny space to leave a space for the people in the cloning pod like in delta and meta because some of them just go afk after dying but in this small map it does not make much sense because cloning is such a tiny space. I feel like removing it is the best option here. Also I have to fix some minor problems. I will do the pr in a bit.

**Comment by jlsnow301** [comment]
Resolved in PR
