### ISSUE TITLE
AI turrets are broken.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#4782]
**INCLUDE THE ROUND ID**
Not relevant.

## Testmerges:

Unrelated

## Reproduction:

AI turrets will not fire at Cyborgs even if you enable the option to, this allows Nuke Ops Cyborgs to hilariously easy cheese the AI, this is a pretty critical issue.

**Comment by Sarchutar** [comment]
Target Cyborgs works as shown in the video below. 
Sidenote: Only Syndicate Assault Cyborgs will get instantly shot at, for the other two modules Target Cyborgs needs to be enabled. (Because only the assault one gets the "silicon" faction removed for some reason)

<details>
<summary>
Video, using latest master
</summary>

https://user-images.githubusercontent.com/53494785/125177920-21beac00-e1e0-11eb-8867-31acc79a3440.mp4

</details>

The thing that is most definitely broken is that turrets will completely stop working if they get turned off manually (Through hand or by turret control panel), by not getting power or if a malf ai controls them.

I blame #4333 for changing processing from
```
if(!on || (stat & (NOPOWER|BROKEN)) || manual_control)
  return
```
to
```
if(!on || (stat & (NOPOWER|BROKEN)))
  return PROCESS_KILL
if(manual_control)
  return PROCESS_KILL
if(uses_stored && !stored_gun)
  return PROCESS_KILL
```
Turrets will not resume processing because we lack tgstation/tgstation#50999 where turrets get a proc which resumes it.
