### ISSUE TITLE
psychiatrist's cat doesn't take some interactions.

### ISSUE THREAD

**Issue by yurara** [BeeStation/BeeStation-Hornet#4909]
## Reproduction:

just get a cat from your psychiatrist beacon. Hurt your cat and try to heal them with normal patches or healing syringes. They are not interactable with that stuff. Only way to heal them is a bruise pack from a first aid kit.
Note: monkeys can be healed with the stuff that cat can't take.

**Comment by BrumalLake** [comment]
this isn't a bug, most animals can only be healed through that method, and monkeys are more advanced creatures that metabolize reagents
no one has ever added a way to heal them with chemicals

**Comment by yurara** [comment]
I see. then it looks less consistency rather than a bug.

**Comment by Sinestia** [comment]
Monkeys aren't simple mobs


they are the actual exception

**Comment by EvilDragonfiend** [comment]
(*the same user of yurara)
Hmm, then, how about giving the cat 9 lives? Since the cat is important for psychiatrists as they can let people pet the cat for making people's mood better, but also their cat is really open to random danger because they don't have their own office room. without the cat, the gimmick really becomes useless.

**Comment by EvilDragonfiend** [comment]
can anyone close this please? I forgot my yurara account to close this.
