### ISSUE TITLE
Dead body placers in random maint

### ISSUE THREAD

**Issue by Isy232** [BeeStation/BeeStation-Hornet#5096]
## Testmerges:

None

## Reproduction:

![image](https://user-images.githubusercontent.com/41198990/129123549-8f29e6ed-a85e-47b7-95e2-59f9999e6240.png)

Whatever this random maint room is, it spawns these "Dead body placers" that are very visible errors. I deleted them here on this round though before I took the image.

**Comment by KubeRoot** [comment]
Found the room in question: `_maps/RandomRooms/10x5/sk_rdm154_butchersden.dmm`

EDIT: The "dead body placer" is `/obj/effect/mapping_helpers/dead_body_placer`, and it seems to only work for placing bodies in morgue trays in the same area, when it finds none it logs to `log_mapping` and stays there.

EDIT 2: I looked at the history of the map and relevant code: the dead body placers were never intended to be used like they were used in the template, the mapper just used them incorrectly and the bug was presumably present since they were merged almost a year ago.
