### ISSUE TITLE
Gas miners seem to break late into the round.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5179]
## Testmerges:

#4543: '[MDB IGNORE] Supercruise Part 2 (part 2 - deconflict edition) - Randomly generated ruins, Infinite shuttle Zs, Economy changes, Partial science refactor, Exploration job.' by PowerfulBacon at commit ebfdaaf741
#5152: 'SSmetrics' by AffectedArc07 at commit de651a4f48

## Reproduction:

I can't really reproduce this, but I have a suspicion that gas miners break after a about an hour, sometimes the oxygen tank becomes completely empty and doesn't replenish.

**Comment by davv1** [comment]
It's not because they break. They produce too less mols and have very low max_kpa variable (max kpa for all tanks is 2500kPa, and they produce 10.39mol every single mining tick).
And this happens on every code, for no reason it's not updated. We should have a bit more oxygen and nitrogen for air, as it gets used fast on highpop...
