### ISSUE TITLE
The Nightmare antagonist can't destroy the light sources with the lighteater anymore.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#5276]
It just can't. Nightmare can hit light emitting objects with the lighteater on the harm intent, this won't damage nor destroy the objects.

**Comment by DatBoiTim** [comment]
> It just can't. Nightmare can hit light emitting objects with the lighteater on the harm intent, this won't damage nor destroy the objects.

What objects are you hitting?

**Comment by IllotAFV** [comment]
It happened in the round, when the Nightmare tried to destroy the glow stick, the scientist with the PDA light on and the hardsuit with the helmet light on.

**Comment by AnCopper** [comment]
Yeah, I can confirm this.

**Comment by Rukofamicom** [comment]
Tested on flashlights and PDA - it just doesn't work anymore.

**Comment by Crossedfall** [comment]
Issue caused by https://github.com/BeeStation/BeeStation-Hornet/pull/4543. 

This should be fairly easy to resolve, the issue looks to be caused by the new `lighteater_act` proc not being properly called after attack (reference below).

https://github.com/BeeStation/BeeStation-Hornet/blob/10ceecde0bdaf0931b943bf4d0c9727fd71eab58/code/modules/mob/living/carbon/human/species_types/shadowpeople.dm#L179-L192
