### ISSUE TITLE
Thresholds increasing severity may not be functional

### ISSUE THREAD

**Issue by Rebelord01** [BeeStation/BeeStation-Hornet#5378]
## Reproduction:

I made a virus featuring Biometallic with the two severity increasing thresholds bet irradiant cell and organic flux however the severity was only four which can be related to irradiant's severity of 3 and organics severity of 1. I've triple checked and made sure that the other symptoms do not have any negitive severity and none of them are fractured

**Comment by KubeRoot** [comment]
Can you list all the symptoms the virus had? It might help with actual reproduction, especially for coders that aren't good with virology.

**Comment by Rebelord01** [comment]
sadly I made the virus pretty late at night and don't remember what I had but i should be able to get on and recreate it with some accuracy soon.

**Comment by Rebelord01** [comment]
![image](https://user-images.githubusercontent.com/34816217/133173764-95db3030-bc34-4a61-8245-d7b11dfc57ae.png)

**Comment by KubeRoot** [comment]
Oops, I forgot to look into this after all, gonna try to reproduce now

**Comment by KubeRoot** [comment]
Okay, I think I figured it out and this is working as intended.

Turns out, severity in symptoms is more complicated than just adding it up.
- If a symptom has 5 or more severity, it's added directly. However, this first check also runs before the other stats are fully calculated, so any severity thresholds will trigger based on stats from symptoms up to the current one from the start of the list.
- If a symptom has 1-4 severity, the severity is added, but **capped to a certain amount**
  - If the symptom has 3-4 severity, it cannot raise the disease's severity over 4
  - If the symptom has 1-2 severity, it cannot raise the disease's severity over 3
- If a symptom has 0 or less severity, it's added directly.

So, the breakdown of how the stats are calculated, note that Biometallic Replication has an undocumented threshold for resistance 4 that increases severity: (Empty symptom name signifies the running total, thresholds only include the stat they change)

| Symptom                 | Stealth | Resistance | Stage speed | Tranmsmission | Severity           |
| ----------------------- | ------- | ---------- | ----------- | ------------- | ------------------ |
| Organic Flux Induction  | **0**   | **-1**     | **-1**      | **-2**        | **2**              |
| Stealth 2               |         |            |             |               | -1                 |
|                         | 0       | -1         | -1          | -2            | 1                  |
| Silicolysis             | **0**   | **4**      | **-1**      | **1**         | **0**              |
|                         | 0       | 3          | -2          | -1            | 1                  |
| Biometallic Replication | **0**   | **1**      | **4**       | **-1**        | **0**              |
| Stage Speed 4           |         |            |             |               | +1                 |
| Resistance 4            |         |            |             |               | +1                 |
|                         | 0       | 4          | 2           | -2            | 3 (4, capped to 3) |
| Necrotic Metabolism     | **2**   | **2**      | **2**       | **0**         | **0**              |
|                         | 2       | 6          | 4           | -2            | 3                  |
| Iraddiant Cells         | **-1**  | **2**      | **-1**      | **2**         | **3**              |
|                         | 1       | 8          | 3           | 0             | 4 (6, capped to 4) |
| Facial Hypertrichosis   | **1**   | **3**      | **3**       | **1**         | **0**              |
| **Calculated total**    | 2       | 11         | 6           | 1             | 4                  |
| **Actual total**        | 2       | 11         | 6           | 1             | 4                  |
