### ISSUE TITLE
Exploration using Charlie Spawners

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#5384]
One of the exploration destination uses charlie station spawners which have mismatched flavor text and directives for their location. You're prompted to set up power and work together with the crew to restore the station... and yet have no means to do this available to you at all. 

The station isn't spawned until an exploration crew arrives and is already clearing out hostile mobs and stripping everything useful from the location, so this really needs to use a different spawner.

**Comment by St0rmC4st3r** [comment]
It is funny when the mission is to detonate a nuke though.

**Comment by Rukofamicom** [comment]
My issue is that the spawner sends mixed messages to the player taking it. It will add to the problem of players ignoring the text that tells them what they're supposed to be and what they're supposed to do.

**Comment by williamcll** [comment]
This, I think Charlie station still isn't on regular bee?

**Comment by PowerfulBacon** [comment]
They are

**Comment by RussianGenCoke** [comment]
Kinda agree, also to boot _none_ of the Charlie computers work save for the RnD console and gene lab. Also, the explorers have a separate objective to Charlie crew when arriving, get the item or nuke the place and gtfo. My solution would be to spawn the object in a bolted room that need to be unbolted by three consoles (releasing the lockdown I guess?) so the Charlie crew and explorers actually work together and have a purpose rather than just being people you rescue after snatching an item
