### ISSUE TITLE
Custom shuttles report "Insufficient engine power to engage supercruise."

### ISSUE THREAD

**Issue by St0rmC4st3r** [BeeStation/BeeStation-Hornet#5423]
Issue reported from  Round ID: 32741 (BeeStation Sage - Roleplay)

Reporting client version: 514.1557
Testmerged #5367 

Shuttles that are only 12 tiles total sometimes report "Insufficient engine power to engage supercruise."
After bumping the thrust value of the engine to a ridiculous number via varedit and lifting off, the console reported 28.2 tons of mass, which should be equivalent to 282 shuttle tiles. 
My most logical explanation is that some abandoned shuttles are loaded incorrectly and get counted in the total number of tiles in the first custom shuttle. I have not tested the "first custom shuttle" yet though.

**Comment by KubeRoot** [comment]
Oh dear, I think I already know what this is. Had this issue on a WS downstream with their shuttle system. Shuttles use `get_area_turfs` to count the amount of turfs on a shuttle - **however**, `get_area_turfs` doesn't use the area passed to it verbatim, but instead *finds all instances of the type of the area passed.*

If I'm correct about it, the shuttle is counting the turfs of **all custom**(?) **shuttles in existence**, instead of just itself.

EDIT: For reference, here's a relevant PR fixing the same issue in an unrelated shuttle system: https://github.com/SinguloStation13/SinguloStation13/pull/77
Though the solution used there might not be good, if I remember correctly it worked just fine.

**Comment by St0rmC4st3r** [comment]
Update, I tried to liftoff with an abandoned shuttle. It is also overweight. Perhaps this affects all preexisting shuttles?
