### ISSUE TITLE
Tool arm implant welder falling off

### ISSUE THREAD

**Issue by pricklytomato** [BeeStation/BeeStation-Hornet#5618]
## Reproduction:
Honestly forgot about this until I found that I took a [screenshot of it](https://imgur.com/gixRT4P).
I just used the welder attachment as normal, but wasn't able to retract it back into the implant. I then called out another attachment and the welder was dropped from my hand. I was able to use the welder still, but I wasn't able to recall it and was actually able to even put it in my backpack.

**Comment by KubeRoot** [comment]
> Honestly forgot about this

How long ago did this happen, roughly? I'm asking because a refactor of arm implants was ported a while ago, changing some things about how they work internally, that might've fixed some issues like this.

**Comment by pricklytomato** [comment]
> > Honestly forgot about this
> 
> How long ago did this happen, roughly? I'm asking because a refactor of arm implants was ported a while ago, changing some things about how they work internally, that might've fixed some issues like this.

It happened on October 1st, I was just a dumbass and forgot to check in properties of the screenshot I took on what the date was.

**Comment by KubeRoot** [comment]
Ah, then no, it should still be relevant. Will look into it if I remember to.

**Comment by KubeRoot** [comment]
I can confirm now, I downgraded my BYOND just to test this, and the issue is present in https://github.com/BeeStation/BeeStation-Hornet/pull/4604. Not sure how did I mess this up that badly, surprised nobody noticed, but I'm gonna try to figure out how to fix this properly.

For completeness: Apparently you can put a tool from the implant in your pocket, take it out and drop it, and from that point it's detached.
