### ISSUE TITLE
Prisoner Management Console just doesnt work

### ISSUE THREAD

**Issue by Kapu1178** [BeeStation/BeeStation-Hornet#5803]
## Testmerges:
#5108
#5679

## Reproduction:
1. Be warden
2. Be logged in
3. Hold prisoner ID
4. Click "Insert Prisoner ID"
5. Nothing happens.

**Comment by KubeRoot** [comment]
EDIT: I got the wrong console, my bad.

Conclusions from codedive: looks like the issue was introduced in https://github.com/BeeStation/BeeStation-Hornet/pull/1623, when the `id_insert` code was refactored out into the proc, at some point they forgot `id_insert` requires the item to be passed in. Because of this, both the UI actions and the `attackby` override fail to actually insert the ID.
This issue affects both the Prisoner Management Console (`/obj/machinery/computer/prisoner/management`) and, to a lesser degree, the Labor Camp Teleporter Console (`/obj/machinery/computer/prisoner/gulag_teleporter_computer`) - in this case the ID can still be inserted by clicking the console.

<details>

<summary>Codedive:</summary>

In `/obj/machinery/computer/prisoner/management/ui_interact`

```dm
dat += text("<A href='?src=[REF(src)];id=insert'>Insert Prisoner ID.</A><br>")
```

In `/obj/machinery/computer/prisoner/management/Topic`

```dm
		if(href_list["id"])
			if(href_list["id"] =="insert" && !contained_id)
				id_insert(usr)
```

...As it turns out, the issue is the same as before my edit:

On `/obj/machinery/computer/prisoner`:

```dm
/obj/machinery/computer/prisoner/proc/id_insert(mob/user, obj/item/card/id/prisoner/P)
	if(istype(P))
		if(contained_id)
			to_chat(user, "<span class='warning'>There's already an ID card in the console!</span>")
			return
		if(!user.transferItemToLoc(P, src))
			return
		contained_id = P
		user.visible_message("<span class='notice'>[user] inserts an ID card into the console.</span>", \
							"<span class='notice'>You insert the ID card into the console.</span>")
		playsound(src, 'sound/machines/terminal_insert_disc.ogg', 50, FALSE)
		updateUsrDialog()
```

Also note:


```dm
/obj/machinery/computer/prisoner/management/attackby(obj/item/I, mob/user, params)
	if(istype(I, /obj/item/card/id))
		if(screen)
			id_insert(user)
		else
			to_chat(user, "<span class='danger'>Unauthorized access.</span>")
	else
		return ..()
```

Especially compared to the base proc:

```dm
/obj/machinery/computer/prisoner/attackby(obj/item/I, mob/user)
	if(istype(I, /obj/item/card/id/prisoner))
		id_insert(user, I)
	else
		return ..()
```

</details>
