### ISSUE TITLE
weirdly self-duplicating virus

### ISSUE THREAD

**Issue by yurara** [BeeStation/BeeStation-Hornet#5834]
## Reproduction:
![image](https://user-images.githubusercontent.com/2096932/142736375-1e8b2bce-aee5-4d5a-b01d-e604f31366aa.png)
![image](https://user-images.githubusercontent.com/2096932/142736381-e7eb3a1e-d6af-44ce-90b9-899a71016e64.png)

I don't know how to reproduct this.

**Comment by zeskorion** [comment]
Gonna need more info than just screencaps

**Comment by EvilDragonfiend** [comment]
I tried to reproduce it, but I can't make it well. I can only recall the situation a bit to provide some clues.

* the virus was made already. I think I didn't name it, that's why it's Unknown.
* I printed a culture after making one into a beaker.
* I think I tried to inject synaptizine to the culture
* or injected the same symptom into the culture

this is hardly reproductive.
