### ISSUE TITLE
Can’t upgrade sleepers with RPED

### ISSUE THREAD

**Issue by HeartwawyHorror** [BeeStation/BeeStation-Hornet#590]
## Reproduction:

Get the correct parts in the RPED and upgrade the sleeper unit.

**Comment by despong** [comment]
did you forget to open the maintenance hatch with a screwdriver you ding dong

**Comment by SomeAngryMiner** [comment]
this is a known issue, actually: since the stasis update, there only two types of sleepers: the unupgraded ones and maxed ones, and im pretty sure the upgrade code for them is gone, so ill get to it once im done with my pr bucket list, since i do miss getting pentetic acid, omnizine and such from sleepers.

**Comment by The-Scout** [comment]
The fix you guys did to oranges sleeper pr didn't actually fix the problem just revert the sleeper code bacck to before the removal

**Comment by The-Scout** [comment]
this is the pr causing it 
https://github.com/tgstation/tgstation/pull/43075
