### ISSUE TITLE
Engiborg can take advanced mop upgrade

### ISSUE THREAD

**Issue by RougeNPS** [BeeStation/BeeStation-Hornet#6168]
## Reproduction: Install advanced mop upgrade module into engi borg.
![Bugreport](https://user-images.githubusercontent.com/84478655/148875303-8bee4149-f794-4ab4-b1f6-16571ddcfbc8.PNG)

**Comment by Sarchutar** [comment]
every borg module can get that upgrade as far as i know. this issue is not limited to the engineering one

i would do this myself but i don't really have time at the moment
<details>
<summary>for anyone who actually wants to fix this</summary>

https://github.com/BeeStation/BeeStation-Hornet/blob/085f501e268f31e909fa96eba73653c319c4afcc/code/game/objects/items/robot/robot_upgrades.dm#L260-L268

lines 266, 267 and 268 have wrong indentation
changing that should fix this

</details>

**Comment by DatBoiTim** [comment]
Will give it a shot

**Comment by DatBoiTim** [comment]
So, further investigation:

TBOH module also likely suffers same issue(Possibly true for all janiborg upgrades?)

**Comment by DatBoiTim** [comment]
Issue was related to indentation.

Issue was present on multiple other modules.
