### ISSUE TITLE
Nightmare Lighteater deletes hardsuits and flamethrowers

### ISSUE THREAD

**Issue by Megaddd** [BeeStation/BeeStation-Hornet#6171]
## Round ID:
35357

## Reproduction:
Be equipped with an atmos hardsuit and lit flamethrower in hand
Be hit by nightmare
Be standing there naked after getting hit

**Comment by BrumalLake** [comment]
waiting for modsuits port

**Comment by ta3370** [comment]
> waiting for modsuits port

#6034 was closed by coder due to conflict fix issues. And has previously stated in that PR not to hold up on fixes due to it.
As far as I am aware, nobody has of yet picked up the Modsuits Port.

As for this itself, it'd make sense if the Lighteater broke the hardsuit's helmlight and unlit/broke the flamethrower. As is I think it yoinks them due to them being lightsources.

**Comment by DatBoiTim** [comment]
> coder due to conflict fix issues.

While that was a factor, I also didn't want to have to maintain the system through at least it's early lifecycle, especially as my time in college is waning.

**Comment by BrumalLake** [comment]
waiting for modsuits port as in the overlay lighting fix
oh that did get merged
