### ISSUE TITLE
Exploration shuttle got deleted while mid flight

### ISSUE THREAD

**Issue by Nostr0** [BeeStation/BeeStation-Hornet#6386]
Issue reported from  Round ID: 36162 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1578

### Severity

Oh shit Oh Fuck

### Short Description

Exploration shuttle got deleted while mid flight and the gear of everyone on board aswell

### Reproduction

1. Start VIP mission
2. Get VIP (player controlled)
3. Click Launch shuttle
4. Shuttle is in mid transit
4.5 Shuttle console said the 3 propulsion engines are offline or something even when we had like 2000 mols of plasma fuel and the engines were fully upgraded with an RPED
5. Get deleted

Image shows when we were halfway deleted
![unknown](https://user-images.githubusercontent.com/10816516/154521888-e5a77ffe-9b16-47d9-a261-75ec5af33055.png)

DC: St0rmC4st3r#0155 said "The z-level started deleting before the shuttle departed, which should never happen"

### Round ID

36162

### BYOND Username

Nostr0

**Comment by PowerfulBacon** [comment]
Looking at it, the issue seems to be because of this:
 - Shuttle left the z-level
 - Z-level was marked as empty
 - Z-level passed the time limit for being cleared
 - Z-level began deleting
 - Shuttle ran out of fuel after z-level started clearing
 - Shuttle docked with z-level in the process of being deleted

Root of the problem comes down to the fuel reserve depletion docking overriding the fact that shuttles shouldn't dock at z-levels in the process of being cleared. (I suspect this happens due to the orbits subsystem updating every 2 seconds, meaning the shuttle run out of fuel during the 2 second period in which the z-level existed on the map but shouldn't have)

Should be simple to fix:
Find the code that docks shuttles when they run out of fuel and don't consider dropping into z-levels that are in the process of being wiped.

Assumed source of the issue (This can point to a z-level being deleted):
https://github.com/BeeStation/BeeStation-Hornet/blob/e00622c804d6bf9583e31a402cb23cd166c0e565/code/modules/shuttle/custom_shuttle.dm#L97

Although if it happened after 5 seconds, then this would make less sense (although I'm pretty certain it still went through the fuel depletion crash proc to get here).
