### ISSUE TITLE
Fireman carried players are un-droppable.

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#6407]
## Round ID:

36265
## Testmerges:
N/A

## Reproduction:
Fireman carry someone and then attempt to drop them, watch in horror as it doesn't work and they are now stuck to you.

**Comment by ryanmunz** [comment]
+1 This is awful. Buckling yourself to a gurney seems to clear it. 

Nothing will fix the memories of having a felinid with no arms and only one leg stuck to me for 20 minutes though.

**Comment by Crossedfall** [comment]
Caused by https://github.com/BeeStation/BeeStation-Hornet/pull/6036

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/6413

**Comment by Tiger-Brows** [comment]
This bug creates a hilarious knock-on effect, because if you lay down while carrying someone, someone else can pick you up. Rinse and repeat until you have a stack of ten or so crew screaming "MAKE US WHOLE", all being carried by one person.
![unknown](https://user-images.githubusercontent.com/100236285/155211883-50484d6d-57f2-4e3d-a3cf-7a7beeb776d1.png)
