### ISSUE TITLE
Label audit

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#6455]
We have about 70 labels right now. Many of them unused.

Good candidates for deletion are (most of them is unused or they are duplicate):
- balance (duplicate)
- bounty (unused)
- code cleanup (duplicate)
- code (unused)
- config (duplicate)
- duplicate (unused)
- enhancement (unused)
- help wanted (unused)
- invalid (unused)
- javascipt (unsued and deprecated by tgui-changes)
- map edit (duplicate)
- needs rebalancing (unused)
- needs review (unused, every pr needs review)
- petty af (unused/duplicate of ided, which is actually a better joke, also meme)
- port (unused)
- stupid felinid changes (unused, meme)
- Untested (bruh)
- Work in progress (unused)

Also, if possible, labels should have standardized names, it's mildly annoying to see one label be lowercase for no reason.

Actions should also be edited to reflect renames.

**Comment by Crossedfall** [comment]
Removed the duplicated. Kept the following unused labels because they are actually still useful descriptors.

- Help Wanted
- Needs Rebalancing 
- Port (should be used more)
- Untested (should be used more)
- ~~Work in Progress~~ WIP prs should just be drafts now, actually. 

Also went through and title-cased all of the labels to make them more consistent (`i ded` is still all lowercase because it's the meme)

The actions should still pull the correct labels, so no need to adjust those. If we notice anything wrong there we just need to edit these two files:

https://github.com/BeeStation/BeeStation-Hornet/blob/master/.github/label.yml
https://github.com/BeeStation/BeeStation-Hornet/blob/master/.github/file_labeler.yml
