### ISSUE TITLE
You can infinitely table and warp someone by using fireman carrying

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#6575]
## Reproduction:
Step 1- Make sure the person you want to fireman carry is a human, and horizontal
Step 2- Climb onto a table next to them and fireman carry them
Step 3- You should get a new off-hand item on your active hand that should allow you to table them as much as you want, it will also allow you to teleport and table them to said table and even warp into people.

**Comment by RDS88-beeman** [comment]
Oh that's not even the best part
-It works on corpses
-You can slam them into tables with harm intent, breaking them very rapidly because it doesn't break your grab and dealing a LOT of brute to the corpse.
-You can use them on pipes, chairs, people, borgs, and the janicart, to warp the flesh-lump to the pipe, chair, borg, or janicart.
-If you gib the corpse, the grab remains intact, and while you can't teleport the nonexistant thing anywhere you can still tableslam it and make lots of noise by repeatedly buckling it to things, since things that don't exist can't be buckled for more than a tick
-Multiple people can grab the same corpse by this method, meaning one corpse can do all this simultaneously
-If a borg builds a table under itself and does this, the recipient gets a phantom "off hand" but it doesn't seem to do anything.
-Piggybacking is worse and not just from a moral perspective here, but I don't know how to recreate these
