### ISSUE TITLE
Black powder Grenades do not explode

### ISSUE THREAD

**Issue by Chessus** [BeeStation/BeeStation-Hornet#6577]
## Reproduction:
![image](https://user-images.githubusercontent.com/10277607/160793575-16448963-e7c3-4947-a25f-7ddfff4227c3.png)
Black powder grenades do no detonate. They will react, prompting the "Sparks rapidly fly" text but then nothing. Not sure how long this has been present, I learnt of this about a month ago. Tested on private and bee server. BP will still explode if heated up in a beaker with a lighter, inside a person when they are heated up and if you heat the reagents up to create BP it will explode after mixing. 

**Heating up the reagents to make Black powder:**

ADMIN LOG: [TuRKeY91](http://127.0.0.1:61372/tmp9600/browseroutput.html?priv_msg=turkey91)/(Judah Garrison)([?](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminmoreinfo=[mob_17])) ([FLW](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservefollow=[mob_17])) at Primary Tool Storage (55, 57, 2) ([JMP](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservecoodjump=1;X=55;Y=57;Z=2)) primed a chemical grenade at Primary Tool Storage (0, 0, 0) ([JMP](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservecoodjump=1;X=0;Y=0;Z=0)) containing: (beaker 1 : Charcoal, 10 | Saltpetre, 15); (beaker 2 : Sulfur, 50);.
You prime the chemical grenade! 3 seconds!
 Sparks start flying around the black powder!
 The solution begins to bubble.
ADMIN LOG: Reagent explosion reaction occurred at nonexistent location. Last Fingerprint: N/A.

**Heating up the beakers with black powder in it:**

ADMIN LOG: [TuRKeY91](http://127.0.0.1:61372/tmp9600/browseroutput.html?priv_msg=turkey91)/(Judah Garrison)([?](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminmoreinfo=[mob_17])) ([FLW](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservefollow=[mob_17])) at Primary Tool Storage (55, 61, 2) ([JMP](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservecoodjump=1;X=55;Y=61;Z=2)) primed a chemical grenade at Primary Tool Storage (0, 0, 0) ([JMP](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservecoodjump=1;X=0;Y=0;Z=0)) containing: (large beaker 1 : Saltpetre, 5 | Sulfur, 5); (charcoal reserve tank 2 : Black Powder, 5);.
You prime the chemical grenade! 3 seconds!
You put the chemical grenade into the medical backpack.
You throw the chemical grenade.
 Sparks start flying around the black powder!
ADMIN LOG: Reagent explosion reaction occurred at nonexistent location. Last Fingerprint: N/A.

**Using pyro grenade:**

ADMIN LOG: [TuRKeY91](http://127.0.0.1:61372/tmp9600/browseroutput.html?priv_msg=turkey91)/(Judah Garrison)([?](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminmoreinfo=[mob_17])) ([FLW](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservefollow=[mob_17])) at Primary Tool Storage (55, 55, 2) ([JMP](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservecoodjump=1;X=55;Y=55;Z=2)) primed a pyro grenade at Primary Tool Storage (0, 0, 0) ([JMP](http://127.0.0.1:61372/tmp9600/browseroutput.html?_src_=holder;admin_token=6626098335708102294942910405997294;adminplayerobservecoodjump=1;X=0;Y=0;Z=0)) containing: (beaker 1 : Charcoal, 25); (beaker 2 : Saltpetre, 25 | Sulfur, 25);.
You prime the pyro grenade! 3 seconds!
 Sparks start flying around the black powder!
 The solution begins to bubble.
ADMIN LOG: Reagent explosion reaction occurred at nonexistent location. Last Fingerprint: N/A.

**Comment by KoboldCommando** [comment]
The underlying issue is that the grenade starts the reaction, creates a delayed callback, deletes itself, and then the callback happens and tries to explode at the location of the grenade, which no longer exists.

This can be fixed by instead creating a datum for the in-progress explosion, and using COMSIG_MOVABLE_MOVED to track any movement of the holder as the timer ticks down, so you can explode in the right location (even if the holder disappears in the mean time).

If anyone else tackles this, also watch for issues arising from black powder in beakers, oil slime cores, oil slime cores in large grenades, and cherry bombs, as they each have very slight variations that can become issues.

**Comment by xurxomario** [comment]
Reported and messed with this a while ago, and heres a reminder that the same code is also breaking teslium grenades for the exact same reason (tho it uses a different function), tries to find it after getting removed, then no zaps happen at all. Same thing happens with any other delayed reaction ever when put into grenades, as all of them use the same function to determine the epicenter of the position when they explode as black powder.

Pretty sure its been broken since the first wave of pyrotechnic reworks, meaning some of the higher ends of teslium reactions cant even be achieved due to lack of space in a beaker to do em, for example.
