### ISSUE TITLE
Soporific shells are insanely OP and security has figured it out

### ISSUE THREAD

**Issue by Oscari-pog** [BeeStation/BeeStation-Hornet#6604]
## Testmerges: 
The following pull requests are currently test merged:
[#6592: 'New original gamemode: carp ops' by Archanial at commit 34f9004d4f](https://www.github.com/beestation/beestation-hornet/pull/6592)

## Reproduction:
1. Print soporific shells.
2. Fire 2 slugs at anyone, through any armor (both stamina, and armor that blocks syringes usually), no matter their stimulants, immunities, anything.
3. They get put to sleep, and if they wake up before you beat them to death, they are forced to constantly move in random directions for a solid 5 minutes.

**Comment by pricklytomato** [comment]
Would be better to just make them not able to go through armor. Sec historically is murder hungry to the point that it's only just now becoming an issue, I think completely removing them is the right step. Removing it upright is just going to push sec one step closer to using lethals instead of using non-lethal alternatives. 

That and I haven't even heard of it being an issue until now and the shells have been around for at least like two years. I've even used them before as warden, only just now today when playing I've seen antags salt over being put to sleep in OOC (and that's how I found out about this "issue" being put up). Just because someone today decided to look up what a shell does and use them doesn't mean it should be removed. This "issue" is more of a thing I'd expect to see on the forums rather than on a place to post about bugs.

**Comment by Oscari-pog** [comment]
> Would be better to just make them not able to go through armor. Sec historically is murder hungry to the point that it's only just now becoming an issue, I think completely removing them is the right step. Removing it upright is just going to push sec one step closer to using lethals instead of using non-lethal alternatives.
> 
> That and I haven't even heard of it being an issue until now and the shells have been around for at least like two years. I've even used them before as warden, only just now today when playing I've seen antags salt over being put to sleep in OOC (and that's how I found out about this "issue" being put up). Just because someone today decided to look up what a shell does and use them doesn't mean it should be removed. This "issue" is more of a thing I'd expect to see on the forums rather than on a place to post about bugs.

Soporific slugs were apparently never intended to penetrate hard armor anyways so this doubles as a bug report

**Comment by OverwatchVoice** [comment]
> Sec historically is murder hungry to the point that it's only just now becoming an issue, I think completely removing them is the right step. Removing it upright is just going to push sec one step closer to using lethals instead of using non-lethal alternatives.

So you're saying that they need a laughably broken non-lethal weapon so that security doesn't murder bome?


The problem is that the confusion the shells inflict is instantaneous (Unlike every other source of confusion, which use reagents to cause the effect), with absolutely no counter, and lining up the second shot is easy thanks to the confusion caused by the first shell. 

Also, any amount of confusion will do to trigger the sleeping effect. You can slip people with space lube and hit them with the shell for an instant knockout.

remember tasers? They were removed from security's equipment for the same exact reason

**Comment by pricklytomato** [comment]
> The problem is that the confusion the shells inflict is instantaneous (Unlike every other source of confusion, which use reagents to cause the effect), with absolutely no counter, and lining up the second shot is easy thanks to the confusion caused by the first shell.

I then propose that in order to print it you'll need to add a chem into the lauthe. Could be just a related chemical to the effect of the shell like morphine, chloral hydrate, or even pax. Just have it require a large amount. It's just as easy to nerf it as it is to remove. Along with making weapon research required, removing it's armor piercing ability (can't even get piercing syringes without having to research them first),
