### ISSUE TITLE
Security Level Signal Handler

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6757]
Security level should have a global signal, instead of looping through all airlocks, airlocks that unlock on red alert should register that signal.

**Comment by Mat05usz** [comment]
Airlocks have a var that when you check access, and it's red alert, it let's you through that door, it isn't looping through airlocks to unlock them (just to display message). However, it does loop through all fire alarms whenever alert changes to update icon, so that sucks and signal might be cool for that.

**Comment by Mat05usz** [comment]
On the other hand, you gotta loop through all of them to send them signals anyways, no?
