### ISSUE TITLE
Reproductive Grey Slime Extracts not working as expected

### ISSUE THREAD

**Issue by bixtopher** [BeeStation/BeeStation-Hornet#6762]
Issue reported from  Round ID: 37745 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1583

Feeding 3 cubes to a reproductive grey is just spawning a single grey slime each time, making it an exact 1:1 of what you put into it coming out, which makes the reproductive grey slime a waste of 10 grey slime extracts and the mature slime it cost to make it

**Comment by EvilDragonfiend** [comment]
I don't get what's the issue at all. All of `reproductive` are supposed to spawn one slime by feeding 3 monkey cubes, and you just made it as a grey version.

**Comment by bixtopher** [comment]
The bee wiki says it gives extracts, not just a new living slime, and
that's what I've experienced in other servers.

**Comment by RDS88-beeman** [comment]
This was an intentional change as a result of https://github.com/BeeStation/BeeStation-Hornet/pull/5989
It's not made clear who asked for it, or who wanted it, and I would certainly call it an issue, but it's not a bug.
Did you know you can upgrade the slime processor with better stock parts to make it output 2, 3, 4 extracts per slime?
That should help.
I'll also be coming out with a guide soon and if this is still open I'll drop a link in here

**Comment by EvilDragonfiend** [comment]
It seems the wiki is just outdated.
