### ISSUE TITLE
Slimes can speak many languages including common

### ISSUE THREAD

**Issue by Dejaku51** [BeeStation/BeeStation-Hornet#6798]
## Testmerges:
[#6788: 'Approximates chatmessage's height and width value' by Archanial at commit 8fe9338e06](https://www.github.com/beestation/beestation-hornet/pull/6788)

## Reproduction:
- Be sentient slime
- Use verb "Open-Language-Menu"
- You can speak most of the languages (same as silicons i think)

**Comment by RDS88-beeman** [comment]
I believe this is the round I gave you a sentience potion. Believe it or not, this is entirely intentional behavior. When a sentience potion is used, it teaches all the languages of the user to the fed mob. This is to ensure the player and mob can communicate. In the case of slimes, they come with their own language, and have it set to this by default, but it can be changed with the verb.
