### ISSUE TITLE
Hydroponics shutters on Fland don't work

### ISSUE THREAD

**Issue by Cartlord** [BeeStation/BeeStation-Hornet#6803]

**Comment by Tsar-Salat** [comment]
> ## Round ID: N/A
> ## Testmerges: None
> ## Reproduction: Go to Fland, enter Hydroponics as a Botanist, click the shutter button and get your Access Denied. I don't know if pressing it closes the shutters when it doesn't deny you.

Are the Kitchen shutters properly set with their button aswell? Possible that Hydroponics button is just a copy of the Kitchen one?

I have no experience as service role on fland

**Comment by Kryyto** [comment]
I couldn't reproduce this issue in skeleton crew, since you get the access to kitchen (I think).
But yeah the shutters were set up as "28" (cook access) and not "35" (botanist access), so I fixed that, should work now.

On a side note, does anyone knows how to start a game without it being as a "skeleton crew" (while being alone) ?
