### ISSUE TITLE
Hyperspace parallax effect is broken

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6853]
The hyperspace parallax effect is broken and has been for a while now.

Intended behaviour:
 - When a shuttle is in flight, the parallax should move quickly.

Current Behaviour:
 - When the shuttle starts flight, the parallax starts moving but then stops and doesn't loop.

(If you fix this and show its working, you can have a free antag token)

**Comment by Mat05usz** [comment]
I think I found why, now the problem is to make the code not stink.

Looking at the code though, it doesn't seem that it was an intended behaviour for it to loop.

**Comment by PowerfulBacon** [comment]
> I think I found why, now the problem is to make the code not stink.
> 
> Looking at the code though, it doesn't seem that it was an intended behaviour for it to loop.

Shouldn't the animation have some flag that makes it loop?

**Comment by Mat05usz** [comment]
Having tried fixing it for some time, I'd rather spend my time on something less frustrating and more productive, however **if anyone wants to tackle this 'bug' (if it is a bug, cause I'm pretty sure it's intended) feel free to DM me on Discord _Mat05usz#8583_** , I'll tell you where to start, what to look for and why do I find it frustrating (maybe it'll save you some time).

> Shouldn't the animation have some flag that makes it loop?

Yeah, and it already uses it. I'll be honest, I tried multiple ways of trying to get it to work, but the loop seems to 'stop' at 'random' intervals, then continuing again. Very frustrating, and since that is an in-built byond function there is also no way of debugging it.

**Comment by Mat05usz** [comment]
The thing about how is it coded in is that it starts the 'speed up effect', then it applies 'motion blur', whatever it is that gradually stops the animation. The original speed up effect already uses looping, and when you remove the stopping part, it starts lagging at random, no idea why.

**Comment by PowerfulBacon** [comment]
I'll give whoever fixes this an antag token
