### ISSUE TITLE
Starlight could probably use overlay lighting due to being a low range

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6987]
Starlight lighting should probably use overlay lighting. Note that when testing this, starlight is disabled in the development config.

**Comment by Rukofamicom** [comment]
This one is beyond me, but I'd like to point out that nightmares should very much still take damage in space with whatever new system gets implemented, if only for the sake of balance. 

Alternatively, nightmares will need to be otherwise adjusted to account for the fact they can just freely jaunt into and around in space.
