### ISSUE TITLE
Seemingly infinite wet floor signs

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#7205]
## Reproduction:
Step 1: Buy a floor sign from the jannyvendor
Step 2: The number of floor signs in the vendor does not decrease
![image](https://user-images.githubusercontent.com/101019561/177395639-7a49a25c-4bf8-4241-bf9a-604e1ef0f422.png)

**Comment by Miliviu** [comment]
The number does not decrease, but you can only grab 12, as the code intends, the bug is only visual
![image](https://user-images.githubusercontent.com/45698448/177629614-5fc946eb-373d-4ff3-88d4-06335e121383.png)

![image](https://user-images.githubusercontent.com/45698448/177629969-8268945c-e02d-4229-93cc-ffac4404be10.png)

**Comment by itsmeow** [comment]
Source of bug: The contraband list contains an item with the same name (caution) and it uses that as the display instead.

**Comment by itsmeow** [comment]
Changed it to use product_path instead of the product name as the key for retrieving stock. PR soon.
