### ISSUE TITLE
Glowshrooms spread extremely aggresively, to the point of placing pressure on server performance

### ISSUE THREAD

**Issue by Oscari-pog** [BeeStation/BeeStation-Hornet#7257]
## Reproduction:
1. Plant a single glowshroom
2. It spreads at a uncontrollable rate
3. Aside from being extremely ugly in general, places pressure on server
4. Realise that there doesnt exist a easy way to get rid of them
5. TTV Botany

**Comment by Dejaku51** [comment]
> 4.Realise that there doesnt exist a easy way to get rid of them

Plant Killer

**Comment by Oscari-pog** [comment]
> > 4.Realise that there doesnt exist a easy way to get rid of them
> 
> Plant Killer

Actually doesnt work on them

**Comment by Dejaku51** [comment]
> > > 4.Realise that there doesnt exist a easy way to get rid of them
> > 
> > 
> > Plant Killer
> 
> Actually doesnt work on them

actually it does work because i was using it myself to get rid off glowshrooms

**Comment by LodedDiper69** [comment]
Even grenading them with plant killer does nothing if they're overtaking the station. Even worse when there are podpeople you need to avoid.

Botanists use glowshrooms to soft grief way too often. Or they release them because "the station is too dark" without asking any superior of course. SOP should be rewritten so they can fired for that.
