### ISSUE TITLE
[Bounty] fun Experimental Cloner expansion

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#795]
I was throwin some random ideas at a wall to see what sticks, and this thingy came up. so let's have a go at it. I would like the following changes/additions to be made to the experimental cloner (currently only obtainable from a random space ruin)
-experimental cloner boards are available via illegal tech or 4 tc from a geneticist uplink. Purchase from a geneticist uplink will have a box containing the boards, a screwdriver, wirecutters, a multitool and a crowbar to switch out the machines with.
-experimental cloners now have the display names normal cloning pods and computers do. This does not change their examine text or the computer's interface
-defect clones are given the objective to be the person they are clones of, and eliminate all impostors (including the original)
-emagging an experimental cloning console gives you the ability to  input one objective for the clone to follow. This objective may become an abductor objective if the clone is defective, chance to decrease the higher the pod is upgraded
-change the experimental clone ruin up a bit- it now automatically locks you in the pod of you step in it, and scans you, before unlocking the pod. It also now contains a locker with clothes, and an EVA suit storage unit. _(If this proves to be too difficult to do, feel free to not include it)_

**Comment by zeskorion** [comment]
augh, that fancy ass bountysource link aint showin up and im too much of a brainlet to fix it

Bounty's gonna be 15-20 bucks when i actually shove the money down fyi

**Comment by ike709** [comment]
Dibs. For realsies. I'll be mad if someone else does my claimed bounty again.

**Comment by SomeAngryMiner** [comment]
i like this idea, silently replacing the clone pod console with this or building one in maint, but i would prefer the machine to be different from the standard experimental cloner, yunno, lore and that.

**Comment by ike709** [comment]
I'm too busy to do this. If it's still available when I'm done with finals, I'll do it then. Until then, first come first serve.

**Comment by eLeCtrOssSnake** [comment]
Seem funny, I like this idea

**Comment by eLeCtrOssSnake** [comment]
I am on it, it's gonna take a while but I'll do it.

**Comment by Bastian0930** [comment]
@eLeCtrOssSnake Are you still doing this? I wanna take a shot at this.

**Comment by eLeCtrOssSnake** [comment]
I actually had a big delay on starting this after I claimed it, but I again failed everything and moved it a bit further because I simply can't handle that much. Will try to make it somewhat complete as soon as I can but I can't promise anything. (I realised I haven't played space station for a month, gosh, yes that's somewhat bad I guess) I am not on the way of throwing it, so I guess it will be alright.

**Comment by eLeCtrOssSnake** [comment]
Almost done, I probably don't deserve anything, but still. I'd wanted to contact you @zeskorion to you know, show it to you, to make it to your liking. Tbh it was one hell of a fuckery, I discovered that dream maker language is a complete fucking garbage dumpster that I should've not touched, but because I touched it, there is no easy way out, so because all my school shit is finished (almost) I can actually focus on working on bee and implementing cool stuff. I apologize for such a big-time waste, I just could've not done it any sooner than that. I sent you a friend request on discord so we can talk or chat so I can host a server for you to showcase(?) it to you.

**Comment by eLeCtrOssSnake** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/1883

**Comment by eLeCtrOssSnake** [comment]
Bruh bruh bruh I hope to release it very soon, not like before bruh bruh bruh bruh bruh.

**Comment by TeomanTheGreat** [comment]
> Bruh bruh bruh I hope to release it very soon, not like before bruh bruh bruh bruh bruh.

Can you make it so the normal experimental cloner gives your clones your antag status too? And make this tator item the board and the materials to make it.

**Comment by eLeCtrOssSnake** [comment]
@TeomanTheGreat Experimental cloner is a ruin only item, which has an increasing chance to make you antag like the traitorous cloner does.

**Comment by eLeCtrOssSnake** [comment]
Should be based.
#2193

**Comment by eLeCtrOssSnake** [comment]
Feel free
