### ISSUE TITLE
Borgs cant strip people or unbuckle them from chairs

### ISSUE THREAD

**Issue by constatinus** [BeeStation/BeeStation-Hornet#798]
So, a sec borg cannot swipe a persons icon on him to strip him before getting him into the holding cell? Crazy stupid! And i mean like, nothing pops up. Also, borgs cannot unbuckle people from chairs.

**Comment by St0rmC4st3r** [comment]
Have you tried to use harm intent?

**Comment by constatinus** [comment]
Nope, will try when i have the time, but i dont think its needed for dragging people's sprites onto you

**Comment by Fronsis** [comment]
This was changed when we ported something from TG, at first i was also confusing on why suddenly i couldn't strip them/unbuckle them, you have to be on harm intent in order to do that. As far as i know it was in the talk to also have this implemented for humanoid players, to give some gimmicks to stealing/arresting but i think the conversation dropped, you can check on the Pull request list to see or the forums.

**Comment by constatinus** [comment]
Okay, will close this issue then as soon as i check this

**Comment by ike709** [comment]
@MarkSuckerberg

**Comment by MarkSuckerberg** [comment]
Aaa, my PR changing that got denied, but as far as I know you NEED to have harm intent on to loot as a silicon.

**Comment by MarkSuckerberg** [comment]
I believe this issue is resolved, as no further comment has been made. Using harm intent most likely works for this.
