### ISSUE TITLE
Becoming a midround traitor as the only online player gives 2 free objectives.

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8125]
## Round ID & Round Date:
41507

## Testmerges:
None.

## Reproduction:
1. Exist?
2. Wait for midround traitor.
3. 2 free objectives, 1 optional objective.
![image](https://user-images.githubusercontent.com/86113712/204111234-84ec638f-3db3-4692-bdf1-d6d40a89ead6.png)
![image](https://user-images.githubusercontent.com/86113712/204111226-41479ec9-b6eb-4609-9e6e-e62e4d262adc.png)

**Comment by Coding-Grape** [comment]
IIRC the way objectives are coded even optional or "gimmick" objectives still have a player they are "attached" to, so objective 3 is choosing you, and 1/2 can't find someone to choose. I dunno why they don't default to stealing shit though.

this is also why sometimes you get new gimmick objectives midround, due to the "target" cryoing

**Comment by itsmeow** [comment]
This is not a bug. If no one is online, there is no one for you to target for assassinate objectives.
