### ISSUE TITLE
Pubby Station shuttle fail

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#8157]
Issue reported from  Round ID: 41609 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

I try repairing the shuttle, somebody call it after I replaced all floor tiles, I was immediately ejected to spaces
![Shutle reparation fail](https://user-images.githubusercontent.com/72167130/205453284-9247d304-a0d6-4e16-b2c7-5fc35473df96.png)
![Rest of the shuttle](https://user-images.githubusercontent.com/72167130/205453287-4273e1b6-5d47-4818-8505-976a96ec2ecd.png)

**Comment by PowerfulBacon** [comment]
I added in an admin message for when this happens so I'd know what causes it, but I didn't have the forsight to actually log that message.
I'm aware of what causes the issue, but I don't know exactly what is causing that cause; it happens when the mobile_ports underlying turf area list (the thing that stores which areas are under each turf of the shuttle) is either null or empty somehow. I don't know how it is becoming null or empty though or why it only happens on pubby station.
