### ISSUE TITLE
Weird Stairs Bug

### ISSUE THREAD

**Issue by Bielogical** [BeeStation/BeeStation-Hornet#8634]
Issue reported from  Round ID: 43031 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

I was thrown into lavaland after going upstairs in Genetics. Durand was blocking the way down, so the only way i could go was up, and i simply clipped into lavaland. Don't know if it can get reproduced tbh

**Comment by itsmeow** [comment]
Based transport method

**Comment by itsmeow** [comment]
Can't find any related runtimes

**Comment by itsmeow** [comment]
If you don't mind, what's your CKEY? Trying to find it in logs

**Comment by itsmeow** [comment]
Ah, I found it. No need.

**Comment by itsmeow** [comment]
I've found the solution I think!
It seems like mech pushing was not properly checking if it was trying to push a mob/object up or down - which due to the weird intricacies of how multiz works meant the the turf it thought was "above" was lavaland (z6 -> z7) instead of correctly determining there was no turf above you. This combined with you somehow having phasing powers or some type of turf that let you enter it from an unexpected direction meant you ended up on lavaland.

Shouldn't happen again.
