### ISSUE TITLE
[15:04:30] Runtime in stack_trace.dm, line 7: Incompatible /datum/component/drift assigned to a /obj/effect/decal/cleanable/blood/gibs! args: [4,0]

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8913]
## Occurance Details

**Round Date:** 2023-04-21

**Round ID:** 43693

**Runtime Information:**
```
proc name: stack trace (/datum/proc/stack_trace)
src: /datum/component/drift (/datum/component/drift)
call stack:
/datum/component/drift (/datum/component/drift): stack trace("Incompatible /datum/component/...")
/datum/component/drift (/datum/component/drift): New(/list (/list))
the gibs (/obj/effect/decal/cleanable/blood/gibs): AddComponent(/list (/list))
the gibs (/obj/effect/decal/cleanable/blood/gibs): newtonian move(4, 0)
the gibs (/obj/effect/decal/cleanable/blood/gibs): Moved(space (125,131,7) (/turf/open/space/basic), 4, 0)
the gibs (/obj/effect/decal/cleanable/blood/gibs): Moved(space (125,131,7) (/turf/open/space/basic), 4)
the gibs (/obj/effect/decal/cleanable/blood/gibs): Move(space (126,131,7) (/turf/open/space/basic), 4)
the gibs (/obj/effect/decal/cleanable/blood/gibs): Move(space (126,131,7) (/turf/open/space/basic), 4)
/datum/move_loop/has_target/di... (/datum/move_loop/has_target/dist_bound/move_to): move()
/datum/move_loop/has_target/di... (/datum/move_loop/has_target/dist_bound/move_to): process()
Movement Loops (/datum/controller/subsystem/movement): pour bucket(/list (/list))
Movement Loops (/datum/controller/subsystem/movement): fire(0)
Movement Loops (/datum/controller/subsystem/movement): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by HowToLoLu** [comment]
Seems like gibbing someone in space causes this, or more accurately: 
It's caused by the movement of a `/datum/effect` such as gibs through a zero gravity environment.

I managed to make the runtime stop by overriding `Process_Spacemove`, but I'm not sure if that's the best way to fix it.

<details>
<summary>The Proposed Fix:</summary>

Code in `code\game\objects\effects\effects.dm`:
```dm
/obj/effect/Process_Spacemove()
	return 1; //We shouldn't drift since that seems to cause problems
```
Result:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/5c8e7bb3-6ab0-43b5-a6bf-c690233bcddf)
</details>

**Comment by PowerfulBacon** [comment]
Surely the drift component should work on effects, so in theory we could just remove the check to ensure that the parent is an effect? Maybe I'm wrong

**Comment by HowToLoLu** [comment]
I debugged the code some more; while the amount of gibs involved varies, error is generally caused by one source, which I confirmed by adding a stack_trace to the return in question.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/52caac37-caac-4e19-bbf9-2489f17f2f34)


But I can't find any duplicate loop additions to `SSspacedrift` while stepping through the gib sequence, so I don't know whether the `existing_loops` used is shared between managers since the gibs invoke a loop call of their own, or if something else is being done.

**Comment by HowToLoLu** [comment]
Alright, I think I fixed the bug- turns out it was due to a signal erroneously unregistered before it should have been, which I'll make a PR for right now.

Sadly: Around 150 humans were harmed in the fixing of this bug.
