### ISSUE TITLE
Useless/Confusing preference menu UX design choices

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8958]
**Preference menu is currently being redesigned to be TGUI by itsmeow, making this to give some feedback on the current pref window to help with designing that**

This is more an issue with design, but I have noticed that we have a lot of preferences that really do not need to be preferences. The design of our preference menu is overcomplicated in general and would be a lot better simplified. Even the options menu could be better off being split into a basic and advanced category.
The preference menu should be as simple as possible for a user that does not need to deal with the extra complexity, with extra complexity being there for people who want it/explore it.

Some of the prefs which I don't see a purpose to having are:
- Ability to toggle outline on/off (I guess it makes sense since you can choose its colour, all personalisation options should be in the same category)
- PDA theme should be an option on the PDA itself
- Toggling income updates
- Toggling crew objectives
- Ambient occlussion toggle

Antagonist preferences:
- These should all be enabled by default, rather than disabled
- Antagonists with a yes/no popup window don't need a preference (it just means you have to turn it on)
- Mentor rat especially makes no sense being a preference (I believe these are only here because of the antag banning system)
- There is a button right in the corner for toggling midround antag but then an entire section for toggling midround antagonists individually which is extremely confusing. All of these midround antags notify ghosts, but then there is another section called ghost-notifying roles which arbitrarilly has some of the other options. (What the hell is stuff like the living legend, why does that need to be a pref, I'll just press no to it if it comes up)
- Preferences for antags that don't even run should not be there. If an admin runs that gamemode, it should just default to on or use a different antag setting like traitor or something
![image](https://user-images.githubusercontent.com/26465327/235342275-38799d42-c5f8-435c-8b88-728d86036190.png)

Character preferences:
- Size is seperated from age and name for some reason.
- Always random name should disable the name box when activated and revert to the previous name when disabled.
- The menu is so tall that you have to scroll, despite half of it being whitespace
- Some more advanced settings such as specific job roll names could probably be rolled into the job selection screen by having preferences specific for those jobs when you toggle the jobs on.
- Same applies for specific job preferences
- Gradient style could be much better explained as to what it actually does, and where the gradient applies to
- Choosing the random body option shouldn't randomise all my prefs, it should choose the random body on-spawn.
- Species menu could be improved by describing the advantages/weaknesses and a short summary of each species

OOC Preferences:
- Why is this seperate from game preferences just to let me toggle window flashing
- The show pull requests option is useless since we don't show pull requests
- Play admin MIDI is useless since the option to disable it by turning it down is in the TGUI options menu

**Comment by EvilDragonfiend** [comment]
antag pref was newly added during TM. It's not easy to rip off immediately because these were all merged into a single category, and I separated them into 3 categories. I will see what I can do more after my refactor TM is merged for that page.
Also, yeah, midround button is on a weird place...

**Comment by itsmeow** [comment]
> Play admin MIDI is useless since the option to disable it by turning it down is in the TGUI options menu

This isn't true actually, it does disable it

**Comment by itsmeow** [comment]
> PDA theme should be an option on the PDA itself

This is the default theme so you don't have to change it every round. It is very much an option on the PDA. I was actually going to move this to character preferences.

**Comment by PowerfulBacon** [comment]
It should be a persistent option on the PDA settings

**Comment by itsmeow** [comment]
If it was persistent it would still have to be a preference of sorts. Preferences belong in the preferences menu.

Good design does not compromise functionality. Removing every slightly less useful preference is not a route to go, rather designing sensible categorization and UI components to simplify them.

**Comment by EvilDragonfiend** [comment]
related PR
* https://github.com/BeeStation/BeeStation-Hornet/pull/9229

**Comment by itsmeow** [comment]
## Changes in Prefs Redux

>Ability to toggle outline on/off (I guess it makes sense since you can choose its colour, all personalisation options should be in the same category)

Recategorized

> PDA theme should be an option on the PDA itself

Not possible to implement per-character in a sensible way then - it's now under the character. Might be possible to move into NtOS but doesn't play super well with datumized prefs that way.

>Toggling income updates

They are kinda spammy but fair - but not removing functionality yet

> Toggling crew objectives

Fair but not removing functionality yet

> Ambient occlussion toggle

performance thing. some potatoes don't like filters.

> Antagonist preferences:
> These should all be enabled by default, rather than disabled

Donee

> Antagonists with a yes/no popup window don't need a preference (it just means you have to turn it on)

I've kept these around as a way to sort of show off what antags we have. Yes, there is not a huge reason to have prefs for midrounds but now that they are on by default I don't anticipate much of an issue here.

> Mentor rat especially makes no sense being a preference (I believe these are only here because of the antag banning system)

This was related to the jobs rewrite TM and is not actually a thing.

> There is a button right in the corner for toggling midround antag but then an entire section for toggling midround antagonists individually which is extremely confusing.

The midround antag pref has been removed. It's a legacy gamemode thing where you could toggle traitor but then it would make latejoins sometimes. The pref is for said latejoins.

> Preferences for antags that don't even run should not be there. If an admin runs that gamemode, it should just default to on or use a different antag setting like traitor or something

I've moved these to a "Legacy Roles" category rather than removing them entirely.

> Character preferences
> Size is seperated from age and name for some reason.

Age/name are not related to the body - All body prefs go in the body section while other traits like age should be on their own.

> Always random name should disable the name box when activated and revert to the previous name when disabled.

TODO. randomization is a mess in general.

> The menu is so tall that you have to scroll, despite half of it being whitespace

Fixed, way less whitespace now

> Some more advanced settings such as specific job roll names could probably be rolled into the job selection screen by having preferences specific for those jobs when you toggle the jobs on. Same applies for specific job preferences

AI core preference only shows when you have AI selected, alternate names are now in their own popup next to the name button.

> Gradient style could be much better explained as to what it actually does, and where the gradient applies to

Now says hair gradient and has sprite previews

> Choosing the random body option shouldn't randomise all my prefs, it should choose the random body on-spawn.

Yeah randomization sucks major ass. It's still bad.

> Species menu could be improved by describing the advantages/weaknesses and a short summary of each species

Added

OOC Preferences:

> Why is this seperate from game preferences just to let me toggle window flashing

Joined into one menu

> The show pull requests option is useless since we don't show pull requests

Downstreams do, and we could very well add it. It could be hidden when the config option is not set or whatever, so that's probably a good idea.

> Play admin MIDI is useless since the option to disable it by turning it down is in the TGUI options menu

Ehhh, the preference prevents the MIDI from even being sent to the client. Also some admin music uses this pref that doesn't use the panel (Play sound file etc)
