### ISSUE TITLE
Weird runtime in plasmamen.dm

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#9000]
## Bug Details
![image](https://user-images.githubusercontent.com/110184118/236853310-56d4a2d9-fde7-4e8c-ac2c-9d9185f55a6c.png)

### Reproduction:

Switch species to Plasmaman, pick an alternative helmet style, spawn in, get several runtimes. I reverted to a version before https://github.com/BeeStation/BeeStation-Hornet/pull/8709/ and it was still happening, and I honestly cannot find what's causing it.

**Comment by tontyGH** [comment]
Just gonna leave this here

It's trying to get the plasmaman outfit from `species_outfits` in `/datum/job/gimmick/` which doesn't have a plasmaman outfit defined

**Comment by HowToLoLu** [comment]
That specific datum `/datum/job/gimmick/` should've been an overridden subtype such as `/datum/job/gimmick/vip`, which says that something is giving the player a job that shouldn't be given- which happens to be `/datum/job/gimmick`.

Now- that is a problem that is best left to #8237 to handle, what we can handle right now is that the runtime is caused by some code that doesn't check if it is null or not, which I'll be PRing shortly.
