### ISSUE TITLE
Holopara item explosion is very bad for a 18 TC item

### ISSUE THREAD

**Issue by JBersB** [BeeStation/BeeStation-Hornet#9188]
## Occurance Details

**Round Date:** 6/6/23
**Round ID:** 44371

**Testmerges**:
NA

## Bug Details
I got a holopara with A rank potential for big explsion
### Expected Behaviour:
I make an item explode it makes a hole in the station and is cool

### Actual Behaviour:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/99930791/32e07ee0-1e1a-4fe6-a929-f1ac8cd11d53)
it didn't even make a hull breach
Holopara exploding doors still worked fine and killed people instantly

### Reproduction:
Get holopara with A rank potential 
Make an item explode
Explode item on floor
Cry as it only explodes one tile and is very small

**Comment by mystery3525** [comment]
The round has not ended yet.

**Comment by CydiaLamiales** [comment]
Likely nerfed as a part of this https://github.com/BeeStation/BeeStation-Hornet/pull/7686

**Comment by JixS4v** [comment]
Pretty sure the point of the holopara explosion is that it gibs the affected but doesn't damage the environment

**Comment by oo7craigmc** [comment]
It's based on Killer Queen from Jojo's Bizarre Adventure.
Here's a video showing it in action several times.

Spoilers for part 3.
https://www.youtube.com/watch?v=K3sjBwqDKW0

**Comment by Rukofamicom** [comment]
I'm apalled by the fact that whoever made the subs for that video decided to translate "Killer queen" which is already english into "deadly queen".  But also the holopara explosion is intended to kill players (like grenades), not cause massive station damage. I don't believe this was a bug in the first place let alone a bug now. 

Does anyone have more recent testing on this bug since the holopara rework?
