### ISSUE TITLE
A bunch of custom food stuff is broken.

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#9199]
Issue reported from  Round ID: 44377 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1589

You can't start a custom toast or sandwich by clicking a plain bread slice with an item. I also couldn't get it to work with a whole loaf of bread; instead it just hides the item inside the loaf. Custom pasta didn't work either. Custom burgers and pizza *DID* work.
And finally, but possibly unrelated, microwaving uncooked spaghetti gives you boiled spaghetti and also gives you back the uncooked spaghetti, duplicating it.

I didn't do an exhaustive test of custom food, but hopefully this is a helpful start.

**Comment by Tsar-Salat** [comment]
> You can't start a custom toast or sandwich by clicking a plain bread slice with an item.
> Custom pasta didn't work either.

Thats because I converted bread & pasta in #8748. I specifically noted it customfood would be broken, as its being elementized at the end of newfood.


> Custom burgers and pizza _DID_ work.

I did not convert these to newfood at the time of this bug report, customfood will no longer be possible with these after #9860 

I am fixing the dupe code at this moment however
