### ISSUE TITLE
[Bug]: Gulag airlocks depressurize to 0 kpa

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#9419]
### BYOND Version

514.1589

### Round Date

2023/07/16

### Round ID

44929

### Test merges

[#9124: 'Enable serverside 515.1609 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

When you use the gulag airlock, it will depressurize to 0 which is lower than even the atmosphere in lavaland. This causes you to get burn damage and sometimes straight up die if you get stuck, which is really annoying for if you actually try to do gulag points
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/101019561/5195ccbc-45f8-4d96-a5d8-b7bd46398079)

### What did you expect?

I expected to not get burn damage and die because of some map design mistake

### Reproducible steps

1. Walk into the gulag airlock
2. You now reproduced the bug

**Comment by HowToLoLu** [comment]
3 points I thought I might mention in regards to this:
- The pressure drop isn't going to outright kill you unless power is cut off from the base while you're going through, at the right time (a less than one second window)

- Additionally the damage is completely negligible from normal use, having less that 20 damage from 3 cycles in and out; and there is an infirmary right over at those white tiles in the picture.

- And finally: Even in the one in a billion chance that something happens and you die in the airlock from depressurization, you have your sensors forced to full, people will come to see what the problem is down there. They even probably have to repair the problem anyways, since only actual damage could cause the airlock to get stuck; causing nobody to be able to come in or out.

**Comment by LodedDiper69** [comment]
Maybe instead of having to heal myself every couple mining threads this obvious design flaw just wouldnt exist in the first place? I don't get defending this. What good does that airlock bring to the server?

**Comment by HowToLoLu** [comment]
While I was only meaning to bring up points regarding the issue- I do think you make a fair point on it not being the greatest by dropping straight to zero. 

The only reason for airlocks to drop to zero is to balance the pressure between two environments; since on fastmos this meant the difference between space walking and space drifting into the sun. However, we don't have fastmos now; and in particular isn't needed on a *planet* with half of an atmosphere of pressure. However, it would still need to go to zero going back in as to not contaiminate the interior air supply...

Returning to a magic fan under the door is crude in my opinion, but would solve this.
