### ISSUE TITLE
[Bug]: Explorer objectives don't always fail when leaving the beacon

### ISSUE THREAD

**Issue by Cartlord** [BeeStation/BeeStation-Hornet#9806]
### Round Date

2023/09/07

### Round ID

45744

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

We went to an artifact recovery mission, and after I died, my teammate took me back to ths station. The objective didn't fail, but we couldn't go back to the beacon, so exploration objectives were impossible for the rest of the round.
There were also "SHIT IS FUCKED" bug-turfs on-site.

### What did you expect?

I expected the objective to fail when we left, instead of sticking around & making the entire job unplayable for the rest of the shift.

**Comment by PowerfulBacon** [comment]
They only fail if the beacon ungenerates to allow you to return. If there is a player at the location or a shuttle then it will not fail the mission until they die or leave the z level

**Comment by PowerfulBacon** [comment]
The objective has to be destroyed in order to fail the objective, so if the beacon despawns then it fails. If the beacon cannot despawn due to a player being at the location (includes charlie crew spawns), a shuttle is at the location or some other things then the beacon will not despawn and you have to complete the mission
