### ISSUE TITLE
[Bug]: Hardsuit helmets act strange in the inventory when you take a hardsuit off.

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#9866]
### BYOND Version

514.1589

### Round Date

9/19-20/2023

### Round ID

Multiple

### Test merges

N/A - reproduced on local

### Describe the bug

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/9423435/c04c7671-1766-426e-a165-945e26c2f0f8)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/9423435/4f9d204d-543c-4b4e-80e3-cd8d6bc64b86)

When you observe someone with a hardsuit helmet (or put one on and take one off yourself), the hardsuit helmet icon appears where it would normally be on the HUD, even if the inventory hud is disabled or not present. 

### What did you expect?

The helmet sprite should disappear.

### Reproducible steps

A: Observe someone with a hardsuit equipped

B: Put a hardsuit on, toggle the helmet on, take the hardsuit off, and disable the clothing inventory overlay.

**Comment by aramix273** [comment]
comparing the hardsuit helmet and reference duplication method used above, it can be observed that a precondition to this bug (items persisting in UI inventory slots) is to have the inventory slot open/visible when the item that is in it is force-(re)moved from it, as in the first attempt with the backpack it did not work because the inventory slots were not visible
